### ISSUE TITLE
If you drag a tab back in the main browser window, Page Shot stops working on that tab

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#1655]
[Affected versions]:
- Firefox 49.0.1 and up
- Mozilla Page Shot 0.1.201609272025

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Page Shot add-on (v0.1.201609272025) is installed on a clean profile.

[Steps to reproduce]:
1  Open the browser with the profile from prerequisite and open two tabs.
2. From one tab navigate to any website.
3. Drag the tab outside the main window to open it in a new window. 
4. Drag back the tab in the main window.
5. Click the Page Shot icon from the main toolbar and observe the behaviour.

[Expected result]:
- The Page Shot overlay is displayed over the page. 

[Actual result]:
- The Page Shot overlay is not displayed over the page.

[Notes]:
- Sometimes is enough to drag a tab in a new window and the issue is reproducible. Even if you navigate to another website, the Page Shot is still not working.
- A "Page Shot went haywire" error is displayed after ~30 seconds (https://goo.gl/Tgz9yz).
- If the tab is dragged back in a new window, the Page Shot will work again.
- Added a screen recording with the issue: https://goo.gl/SbCJDa.

**Comment by ianb** [comment]
Apparently the SDK tab objects are just broken after a tab moves.  Stuff doesn't work, workers can't attach properly, tab events don't fire.  Reloading doesn't fix it, so we can't even push users to do that in order to resolve the issue.  The only decent way to handle it is to open the current page in a fresh tab.  It's not easy to detect the case, so I'm not sure if we can put up an appropriate error either.

Throwing back into triage to consider what we want to do with this given the difficulty.

**Comment by SoftVision-CosminMuntean** [comment]
Closing this issue due to the fact that is no longer reproducible on latest Screenshots version.
