### ISSUE TITLE
[Annotations] Create an interface to let users annotate shots

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#1849]
Looking for a UX spec for a feature in page shot that lets users augment shots by drawing or captioning them...features should include:
- [ ] the first time a user takes a shot, we should introduce and highlight this feature
- [ ] the feature should be extensible meaning that we could add different drawing options over time
- [ ] it should allow the user to set type
- [ ] it should allow the user to change font sizes
- [ ] it should allow the user to draw basic shapes (square, circle, rectange, arrow)
- [ ] it should allow the user to draw freehand
- [ ] it should allow the user to set colors for all of the above

Our goal here is to get a complete spec and then work toward implementing a minimal version as a test to see if we want to proceed with a full implementation.

**Comment by ianb** [comment]
In #1847 we got a request from @caspy7: "Features I would introduce for discussion include: Cropping, insert text, free draw, lines, arrows, Boxes (empty and translucent (highlighting)), and the ability to manipulate/resize until after a save."

**Comment by ianb** [comment]
Some examples ([1](https://bug1296271.bmoattachments.org/attachment.cgi?id=8782429), [2](https://bug1296271.bmoattachments.org/attachment.cgi?id=8793676)) are offered in [this comment](bin/build-scripts/sub_rdf_checkout_version) on #1616 (another ticket about this topic).

**Comment by ChenMorpheus** [comment]
I like this idea. However, from UX perspective, we would suggest creating a basic annotation UX spec first, such as text and arrows mentioned in #1847 or #1616, and then expand the functionality if the minimal version is a great demand. Besides, we definitely will consider the flexibility while we are working on the minimal version. What do you think?

**Comment by johngruen** [comment]
@ChenMorpheus, Yeah, that sounds good to me. As long as we make sure that whatever the minimal solution is, there is room to expand it.

**Comment by wresuolc** [comment]
Moving this in with all the other Annotations bugs

**Comment by wresuolc** [comment]
(actually, maybe forward dupe to #3112)

**Comment by ckarlof** [comment]
I ran into a Firefox Screenshots fan IRL. He loved it, and being able to annotate, markup, and draw on Screenshots is the feature that would take it to 11 for him.

**Comment by stratosgear** [comment]
I would also definitely add to the list the ability to blur/obfuscate part of the screenshot.  This is the annotation task that I most often perform when I annotate a screenshot.

Hopefully it will be helpful to many other people, too...

**Comment by ZyptosKid** [comment]
One of the bugs I noticed is the fact that when you take a screenshot that requires you to scroll (ex. an article), if the website had a sticky scrolling navbar, it will appear in the middle of your screenshot every single time.

Suggestions:
A) Freeze the page in a pre-screenshot snapshot and then allow the user to "screenshot" from that. Effectively, the user would be just cropping the previously taken screenshot in reality.

(That reminds me, an option to re-crop the screenshot should be added to the rest of the retouch options like drawing and marking etc.. it would be nice)

B) Alternatively, you could allow the (save/copy/discard) buttons to float to the top or to the side instead of staying always on the bottom of the cropped frame. This allows users to scroll back up pulling the buttons along with them and avoiding the sticky navbar altogether.

**Comment by ZyptosKid** [comment]
an option to re-crop the screenshot should be added to the rest of the retouch options like drawing and marking etc.. it would be nice
