### ISSUE TITLE
Notification icon for errors

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2239]
When errors occur we're going to pop up a notification.  We should have some error icon to go on it.  I can't find much information on expected sizes.  Our other icon is 32px and seems fine.

Probably just a `!` or something simple is all we need.

**Comment by johngruen** [comment]
here's a screenshot of an  offending error message. We want to have a little icon here.

<img width="1179" alt="screen shot 2017-03-07 at 6 46 32 pm" src="https://cloud.githubusercontent.com/assets/3323249/23683374/acaac766-0366-11e7-8431-6537a9f13f7d.png">

**Comment by ianb** [comment]
It looks like a notification now, not a popup (that was the SDK version)

**Comment by TLHuang** [comment]
Here is the current design for notification

![4 3 notification for error](https://cloud.githubusercontent.com/assets/4092794/23939737/08e9d602-099d-11e7-8e7d-75028254d9fe.png)

For the layout, please refer to [the measurement -> 4.3 Notification for errer](https://www.dropbox.com/sh/sdxpisu3x2uflp3/AADbfr0FnbKarpsh_zmtqLKxa?dl=0), and the illustration is updated [here](https://www.dropbox.com/s/lczxn059kufzkcf/img-fox-placeholder.svg?dl=0). Just a reminder, the current fox illustration you seen on the screen is a placeholder, we are still waiting for the update from Sean Martell.

**Comment by wresuolc** [comment]
We're unable to do a popup like that in a web extension.  Instead we've been using the built-in notifications.  For this we'll need a small icon that will fit in the regular notifications.  /cc @TLHuang @johngruen

**Comment by ianb** [comment]
The icon we need is one that fits in the same place as the copy icon in this popup:

![image](https://cloud.githubusercontent.com/assets/44390/24376503/b735bc9a-1301-11e7-98c0-fe390786228d.png)

**Comment by ckprice** [comment]
@ckprice will hunt down an icon, but not a blocker.

**Comment by TLHuang** [comment]
Hi, may I know why we can use popup when it was on Test Pilot, but now we can only use built-in notification for Firefox Screenshots? I can provide an icon for the notification, just want to know if it's the only way we can do.

**Comment by 6a68** [comment]
@tlhuang Yup, we removed the SDK code and ported to a webextension, which doesn't support doorhangers

**Comment by ChenMorpheus** [comment]
Notification serves as a message to notify users, but it's not for error cases, especially the notification might be pretty far away from where users trigger it, so it would be inappropriate to have notification here.  

Is there any alternative solution or will webextension support door hanger later?  If not, since we won't provide the reason why it's unavailable, I would prefer to have an unavailable badge or only disable the icon on the toolbar to imply Fx Screenshots is not able to be used at this moment. You can check the mockups below.

![2017-03-30 3 17 57](https://cloud.githubusercontent.com/assets/18019946/24492028/6f47a71a-155c-11e7-9ea2-18841d6c0b6a.png)
