### ISSUE TITLE
Create Bugzilla component

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2361]
We should request a Bugzilla component for Page Shot.  This should probably happen after we have a confirmed name.

**Comment by wresuolc** [comment]
AMO successfully stopped using their bugzilla link.  This will make us have to triage in two places.

**Comment by ianb** [comment]
AMO is an example of not having a Bugzilla component, but I'm not sure if we should copy that.

**Comment by ianb** [comment]
We'd rather avoid this, but we should ask Release Management

**Comment by ckprice** [comment]
We're going to close this until we have a need for it.

**Comment by 6a68** [comment]
It seems useful to have a Bugzilla component just for special cases:

- exporting code into firefox
- filing security bugs

Reopening to discuss.

**Comment by 6a68** [comment]
Bug filed to add server and addon components, with the same "please use github" warning message that's shown when filing an AMO bug. https://bugzilla.mozilla.org/show_bug.cgi?id=1361870

**Comment by pdehaan** [comment]
Will any of the code be moving from GitHub to m-c, or is everything staying in GitHub?

**Comment by 6a68** [comment]
> Will any of the code be moving from GitHub to m-c, or is everything staying in GitHub?

Everything is staying in Github. The only uses for the BMO components are for secure bugs, requests to land code in m-c, and (if ops wants) requests to release the server code.

We're going to have the same kind of warning label in the bugzilla form for these components that you see if you look at the AMO input form; see https://bugzilla.mozilla.org/enter_bug.cgi?product=addons.mozilla.org

**Comment by 6a68** [comment]
This work was done in https://bugzilla.mozilla.org/show_bug.cgi?id=1361870.

I originally asked for the same yellow warning banner shown when you open the new bug form for the addons.mozilla.org product:

<img width="882" alt="screen shot 2017-05-25 at 12 49 38 pm" src="https://cloud.githubusercontent.com/assets/96396/26467776/d980b3ac-4148-11e7-8538-a7499b17df8f.png">

Unfortunately, it turns out that's not supported for components, like Screenshots (which is under the Cloud Services product). The BMO team is working on this, but for now, we just have warning messages in the component descriptions, which are visible in the new bug forms:

## Cloud Services product / Screenshots component

<img width="973" alt="screen shot 2017-05-25 at 12 54 19 pm" src="https://cloud.githubusercontent.com/assets/96396/26467933/7154eb94-4149-11e7-98ac-2902fc239df7.png">



## Cloud Services product / Server: Screenshots component

<img width="980" alt="screen shot 2017-05-25 at 12 53 59 pm" src="https://cloud.githubusercontent.com/assets/96396/26467917/643dd07e-4149-11e7-9d7f-8fc3b36640c4.png">
