### ISSUE TITLE
Ensure authentication before navigating to My Shots

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2415]
In #2414 we want to lazily log you in if you visit My Shots, but we have two patterns that get you to My Shots from the add-on, and we can ensure a login before visiting.

The first case is the My Shots button on the selection screen.  The second is hitting the Page Shot button from about:newtab.  Calling `auth.authHeaders().then(...)` in these cases will ensure the request is authenticated.

#2414 will still allow a user to bookmark My Shots or revisit it from the awesomebar and be authenticated.

**Comment by dannycoates** [comment]
> Calling auth.authHeaders().then(...) in these cases will ensure the request is authenticated.

We'll need to do more than just this. It's possible for `initialized` to be `true` in the addon without there being an auth cookie set. A trivial example is clearing your cookies after you've previously been logged in. Instead of relying on `initialized` we could check whether the cookie is present, but we'd need `cookies` permissions.
