### ISSUE TITLE
Create perf-html profile, and platform performance review 

### ISSUE THREAD

**Issue by ckprice** [mozilla-services/screenshots#2554]
From Ehsan

> The basics are pretty simple: go to https://perf-html.io, install the profiler add-on and start profiling using the instructions on that page!  We don't unfortunately have a lot of great documentation at this point due to the lack of bandwidth to produce it.  Sorry about that.  We're trying our best to move fast on all fronts here but we're really starved for choosing what to work on.  :-(

> Last Friday at the Quantum Flow work week here in Toronto, I gave an informal talk about how to use the Gecko Profiler since people were interested in seeing how I use it.  I didn't have any slides or any specific profiling scenario prepared so I decided to profile Firefox live and delve into a couple of scenarios in the parent and content processes.  The presentation is being uploaded right now and will be available at this link once finished: <https://air.mozilla.org/gecko-profiler-introduction/>.  I hope this will be a good starting point.  If people have questions about how to use the profiler and how to read the profiles, I and others hanging out in #flow would be happy to help answer questions!

Ref: https://mail.mozilla.org/pipermail/firefox-dev/2017-April/005262.html

**Comment by ckprice** [comment]
Maybe @ehsan can help us here?

**Comment by ehsan** [comment]
mconley and I looked at the code this briefly on IRC, and I have some suggestions for what to look at.  Please note that Web Extensions APIs are pretty new to me so there may be things I have missed.  Also, I'm very bad at keeping up with Github notifications...  :-)  Although I'll try to open a tab to this issue for a couple of days to see further comments here.

* Is this fast even with arbitrarily large images? https://github.com/mozilla-services/screenshots/blob/master/addon/webextension/background/main.js#L148  In general, doing things like this where the length of the operation depends on the size of some content can result in performance issues.
* When does this work happen?  https://github.com/mozilla-services/screenshots/blob/master/addon/webextension/background/selectorLoader.js#L2 Does the add-on do this for all pages?  Or only for pages where the user wants to capture a screenshot?  It's not ideal if the add-on injects a frame script or some such into all pages that the user loads before they interact with the toolbar button in order to take a screenshot.
* Has this code been tested for performance? https://github.com/mozilla-services/screenshots/blob/master/addon/webextension/selector/documentMetadata.js#L1  Any reason why the DOMMetaAdded event isn't being used instead?  That seems much more efficient than running these selectors over and over again...

**Comment by ckprice** [comment]
Updated the title a bit, and adding a question here from the the Intent to Ship thread

> Does the add-on inject a frame script into every page?  Or only into the pages that the user wants to take a screenshot from?

**Comment by dannycoates** [comment]
> Does the add-on inject a frame script into every page? Or only into the pages that the user wants to take a screenshot from?

It does not inject into every page. It injects as a result of a user action to start a screenshot: toolbar button, context menu, (possibly) keyboard shortcut.

**Comment by 6a68** [comment]
I'll work on generating some profiles today and ping ehsan on irc or email with questions.

**Comment by 6a68** [comment]
Looking at this right now, since it's the other kind of perf issue that could derail landing in 55

**Comment by johngruen** [comment]
@6a68 have you been continuously looking at this since May 25th?

**Comment by wresuolc** [comment]
If this comes back up we'll handle it on a per-case basis.
