### ISSUE TITLE
Toolbar button placement for Screenshots

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#2560]
It turns out that adding a default toolbar button for Screenshots won't make the button appear for users who have customized their toolbar. (I'm not sure how many users have a customized toolbar.)

@MattN pointed out that we could instead use the UITour code to let users opt into Screenshots, by clicking a button in some kind of screenshots marketing page.

If we really want all users to see the Screenshots toolbar button, we'll have to write special code to insert the toolbar button.

**Comment by mattn** [comment]
I'm not.

**Comment by 6a68** [comment]
Sorry, @mattn!

**Comment by mattn** [comment]
NP.

**Comment by mnoorenberghe** [comment]
Sorry to MattN, I'm @mnoorenberghe on Github.

So there are three different options for default placement:
1) Insert the button in the toolbar/menu at a specific position for all users and also place it in the default placements so that it remains there if they reset to defaults in customization mode.
2) Add the button only to the default placements which means that users who have never customized any region (e.g. toolbars or menu panel) get the new button which includes new profiles.
3) Don't add the button to default placements and use [Mozilla.UITour.addNavBarWidget](https://public-artifacts.taskcluster.net/XM6HspVWSRWbx5Nk9aXewQ/0/public/jsdoc/Mozilla.UITour.html#.addNavBarWidget) to add the button to the navbar from a [page running UITour](https://dxr.mozilla.org/mozilla-central/source/browser/app/permissions) e.g. snippets, SUMO, or any page on www.mozilla.org e.g. a marketing page when a user opts-in.

I think (1) and (2) should be used sparingly and with a lot of thought (at least for toolbars) since users have traditionally been sensitive to new buttons in their UI.

**Comment by johngruen** [comment]
@mnoorenberghe agree that 1/2 should be used sparingly, but this might be one of those cases.

So that i understand option three better, the flow would be:
1. User has go to to a marketing page
1. User is prompted to do something (what exactly? enable the add-on? move it from the overflow menu to the toolbar?)
1. Add-on shows up in the toolbar?

I'm a little unclear about the second step here.

**Comment by johngruen** [comment]
additionally, i'm curious how we would drive people to the marketing page from which we could call the `addNavbarWidget` method. If i understand correctly, the add-on would already be running, so we could potentially fire a tab to open when a user chooses to enable the add-on.

I suppose we could then prompt the in-product on-boarding.

New Session -> Tab Opened on screenshots.firefox.com -> User clicks button with `addNavbarWidget` callback -> Screenshots moves into toolbar -> we call `showHighlight` method.

Gotta say, i don't hate this idea, as it might let us be a little less aggressive about forcing Sceenshots on people.

**Comment by 6a68** [comment]
We talked about this in the morning meeting, we're going with option 1. At the end of the day, we were asked to ship this in 54, which entails really shipping the feature to all of our users.

I think there might be some lurking discomfort with the way features have been added to desktop in the past, and I'm not sure Test Pilot features are perceived as importantly different, but they are: we have quantitative evidence that users like the screenshots feature. We didn't have this for Hello or Pocket. I think it would be good for Test Pilot folks to maybe give a brownbag talk sometime soon to make it clearer that we're trying to do product development in an iterative, data-driven way, and to give Firefox devs a chance to ask questions and offer input about the right way to add new features to the browser.

All that said, closing this bug, but let's keep the conversation going, @mnoorenberghe :+1:

**Comment by mnoorenberghe** [comment]
I guess an option 4 related to option 3 is to show some other first-run UI for the user to opt-in to the toolbar button, not necessarily in-content with UITour.

> So that i understand option three better, the flow would be:
> 
>     User has go to to a marketing page

Right, but we can open that page for them (e.g. Fx whatsnew page after a version upgrade or the extension code can open the tab itself), about:home snippets can also be the UI.

>     User is prompted to do something (what exactly? enable the add-on? move it from the overflow menu to the toolbar?)

The UI can be whatever we want… the webpage would just call the API to put the button on the user's toolbar when appropriate. I'm suggesting that for (3) you would ideally have user interaction e.g. ask them if they want to try the awesome new screenshot feature and have a button in the webpage which calls the API to add the button to the navbar. We did this for the Forget Button in Fx42(?).

>     Add-on shows up in the toolbar?
> 
> I'm a little unclear about the second step here.

Yes, the API will place the screenshot button in the navbar.

**Comment by mnoorenberghe** [comment]
> We talked about this in the morning meeting, we're going with option 1. At the end of the day, we were asked to ship this in 54, which entails really shipping the feature to all of our users.

To be clear, that's fine with me (though I know people will complain, which isn't news) but it was apparent to me based on the IRC discussion that the options weren't considered especially because it seemed like (2) was being implemented when (1) was intended. I basically wanted there to be an explicit decision ideally including UX/Product that gave this the green light.

> I think there might be some lurking discomfort with the way features have been added to desktop in the past, and I'm not sure Test Pilot features are perceived as importantly different, but they are: we have quantitative evidence that users like the screenshots feature.

As you know, "evidence that [a large proportion of] users like [it]" obviously doesn't mean "all users" want it though. It's the people that won't want it (or think they don't want it) that I want to be considered in the decision.

> We didn't have this for Hello or Pocket. I think it would be good for Test Pilot folks to maybe give a brownbag talk sometime soon to make it clearer that we're trying to do product development in an iterative, data-driven way, and to give Firefox devs a chance to ask questions and offer input about the right way to add new features to the browser.

Anyways, it sounds like the options have been evaluated and relevant parties have been consulted so let's ship this thing :) 

(_In case it's not clear, my feedback was not as much about Fx Screenshots but about adding new toolbar buttons in general_)
