### ISSUE TITLE
Add option to copy image (not just link) *to* clipboard

### ISSUE THREAD

**Issue by wlach** [mozilla-services/screenshots#2582]
For pasting page shots into github or irccloud (for example), it would be pretty nifty to have an option that just copied the image content directly to the clipboard.

**Comment by anubhavmax** [comment]
As raised by some of the fellow community members, the "Save" button should provide sufficient information to the users that their screenshots are being saved on Firefox's server, either through the icon or through a notification informing the users before the screenshot is actually saved. This approach would align with Firefox's overall mission of User Privacy.

Further, I personally feel that even though "Save" and "Download" are two strong use cases, the screenshot feature could be made a lot more powerful by providing the user a direct option to copy the image to the clipboard and use it wherever required.

This use case is specifically strong for students, researchers and business users who are consistently involved in browsing the web and creating documents and presentations (A core use case for using screenshot feature for an area of interest rather than the whole screen). The Windows snipping tool has exactly alleviated this problem where the user can select a section of the screen and straight away copy the section to any target document that they might be preparing.

The current user journey for Firefox users in that segment is as follows -
1) Visit Webpage
2) Click Screenshot option
3) Select the section to copy
4) Download/Save the image
5) Click on Download button
6) Open Download folder
7) Search for the downloaded screenshot
8) Select the screenshot
9) Copy or drag the image on to the target document (DOC or PPT)
10) Go back to Firefox to continue work

This user journey involves significant amount of active window shifting between Firefox, Download folder and Target Document as well as file dragging, that adds to user pain points.

A direct "Copy" option would have an user journey as follows -
1) Visit Webpage
2) Click Screenshot option
3) Select the section to copy
4) Click the copy button or Ctrl C
5) Click paste or ctrl V on the target document

This journey involves a single window change from Firefox to Target Document and no file dragging at all. A sample screenshot of how the added functionality might look like is as follows.

![sample](https://user-images.githubusercontent.com/29961407/27933901-170ebb26-6258-11e7-8aa4-01a3e392b451.png)

**Comment by johngruen** [comment]
Hey @wlach @anubhavmax we've been feature frozen for a bit now as we clean up for 55 launch, but this is a good idea and i'd like to see it done. We'll add this feature into our planning for subsequent releases.

**Comment by wlach** [comment]
@anubhavmax just fyi, one alternative flow would be:

1. Save the shot
2. From the shot, hover over it, right click and select "copy image"
3. Paste where desired

Not as good as a proper copy button but at least a little easier than downloading, etc.

**Comment by anubhavmax** [comment]
@wlach Yes, that's a current hack. Thanks for pointing out. But I am still concerned about the fact that clicking on the Save button would store the screenshot on Firefox's server, something that won't go well with privacy concerned users whom Firefox appeals to.

A proper Copy button would mitigate the privacy concern too. :)

**Comment by feinstein** [comment]
I would like to add that it would be better if we could Copy the image instantly,  without having to wait for its cloud upload to finish.

**Comment by kidwm** [comment]
FYI:
https://bugzilla.mozilla.org/show_bug.cgi?id=1356543
API is already available in WebExtensions

**Comment by wow23** [comment]
this needs to happen, who really wants to save an image to share it later, really.

**Comment by sha-265** [comment]
Agreed.

**Comment by sivaniv** [comment]
Hi all,
I also agree that copy to clipboard is much needed feature. The majority of other extensions have this feature. It is a pity that the "Out of the box" screenshot solution lacks it.

**Comment by johngruen** [comment]
@chenMorpheus, can we get a proper UX treatment for this. We should also consider the appropriate control changes for shot pages.

**Comment by youwenliang** [comment]
Some quick ideas here: https://mozilla.invisionapp.com/share/D5DTW7LRX

For proposal A, every time there's a cropping area we automatically copy the image to user's clipboard. (potentially triggers too many copy image event...)

For proposal B simply adds a copy image button to the action button list. If we think there are too many action buttons then we should consider using a dropdown menu to allow users to select the action they want (Download or Copy Image or Save to my shots).

**Comment by sivaniv** [comment]
Option B sounds better. 
Some thoughts regarding dropdown menu. 
Adding it will result more clicks/manipulations from user to get the desired action which isn't that good considering that actions are pretty common and preferred to be selected via single mouse click. Currently there are only 4 buttons which isn't that much to hide them under a dropdown.
Maybe Button label could be removed? Button icon itself is pretty recognizable. Also this will put new button on the par with remaning-ones, style wise

**Comment by SEE-ICT** [comment]
Just to follow up on anubhavmax's comment re privacy, it's important to us at least that any copy-to-clipboard capability of the screenshot function have an option to send nothing at all to the cloud. We won't use the function otherwise.

**Comment by feinstein** [comment]
I am against an "auto-copy" option, what if I already have something on my clipboard and I dont want to lose it, over the new copied image? I rather click on "copy" or a "crop+copy" shortcut that can speed things up ONLY when I want it.

**Comment by youwenliang** [comment]
Agree. We should go with the button proposal, here are some options to consider:
![image](https://user-images.githubusercontent.com/8919308/31477460-bde4ee6a-af3e-11e7-835b-338a0392a15f.png)

**Comment by Acid-Crash** [comment]
Hi all,
I agree with suggestions before.
Icon-only version looks best, "Copy"+Icon comes after and "Copy Image"+Icon is least pretty choice.

**Comment by feinstein** [comment]
Could you also make "ctrl+c" a shortcut to copy the cropped image? This would speed things up

**Comment by nyuszika7h** [comment]
The second option in proposal B ("Copy") looks best to me, but a Ctrl+C shortcut would be nice, then it wouldn't matter that much.

**Comment by feinstein** [comment]
For good usability, specially for inexperienced users, even with the ctrl+c shortcut the copy button must be present.
Many users won't realize they can just ctrl+c and have it copied.

**Comment by nyuszika7h** [comment]
Yes, I wasn't suggesting not having a copy button. I meant then it doesn't matter that much which design is used.

**Comment by eyaler** [comment]
would be nice to allow both copy with button or with ctrl-c
would be nice to allow both copy from the capture screen, and from the screenshots library

**Comment by youwenliang** [comment]
Here's the measurement for the icon+"copy" and icon-only version:
https://mozilla.github.io/testpilot-assets/Firefox_Screenshots/FFSS_Copy/
We could do a quick A/B testing to test out the buttons.

The copy icon could be found here: http://design.firefox.com/icons/viewer/

**Comment by ChenMorpheus** [comment]
eyaler commented:
>would be nice to allow both copy with button or with ctrl-c would be nice to allow both copy from the capture screen, and from the screenshots library

@youwenliang I believe this is another thing we need to take into consideration. Could you take a moment to work on this idea?

**Comment by chenba** [comment]
@kidwm thanks for that bugzilla link btw

**Comment by eyaler** [comment]
is there a copy button also in the my shots library?
how about binding with ctrl-c?

**Comment by techtonik** [comment]
I need this. =) So when it is going to be released?

Image | Vote
------------ | -------------
![image](https://user-images.githubusercontent.com/515889/33206631-e70b2788-d11b-11e7-886e-80f526656a7a.png) | :+1:
![image](https://user-images.githubusercontent.com/515889/33206746-520eeef2-d11c-11e7-8d16-ec1c6da18e1d.png) | :heart:

**Comment by fgutmann** [comment]
For me it would be strange to have the "copy" text next to the button.
Currently there are two types of buttons there:

1) Icon Only - Gray
2) Icon+Text - Blue

Introducing the copy button with text, would create a third type of button.

IMO if adding the text to copy it would only be consequent to also add it to "Download" and possibly also to "Cancel".

**Comment by iceuponfire** [comment]
@techtonik it has landed on nightly ! I agree adding ctrl+c would be awesome.

**Comment by chenba** [comment]
@iceuponfire ctrl+c is included.

**Comment by iceuponfire** [comment]
I'm running nightly 59.0a1 64bit win10 (this hour patch).
I'm selecting a zone and then press ctrl+c and there's nothing to paste. Maybe this feature hasn't landed yet on nigthly?

**Comment by chenba** [comment]
It's working for me.  Did you get a notification when you ctrl+c?

**Comment by iceuponfire** [comment]
I confirm you that i do not receive notification when i press ctrl+c (nothing happen, the grey zone stay on screen), however i do get one when i click the new copy image button.

**Comment by chenba** [comment]
@iceuponfire Do you see any errors in the console tab of the developer tools (F12 to open it) when try it?

**Comment by youwenliang** [comment]
@chenba Does it work on Mac? (⌘command + c)

**Comment by chenba** [comment]
@youwenliang Yes it should.  But since I don't have a Mac, I cannot verify personally.

**Comment by 6a68** [comment]
@chenba It's really helpful to have all three OSes available when working on Firefox bugs. You should be able to ask for a mac loaner via [servicedesk](https://mozilla.service-now.com/sp?id=sc_cat_item&sys_id=bcd5f501d8c43400dc7e3d9bdc8f397d).

**Comment by Softvision-CristinaBadescu** [comment]
I've tested this on Mac 10.12.6, on Screenshot 25.0.0, using latest Nighlty build 59.0a1 (2017-12-04) and the "Command + C" key combination didn't work: the screenshot wasn't copied to the to clipboard and the "Shot Copied" notification didn't appear. 
This issue is not reproducible on Windows 10 x64 or on Ubuntu 14.04 x64.

**Comment by chenba** [comment]
@Softvision-CristinaBadescu Thanks for verifying.

I've filed a separate issue for this: #3879

**Comment by iceuponfire** [comment]
@chenba sorry for answering so late but i can confirm you that ctrl+c still does not work, when i press ctrl+c there is no error message on console. However i dont know if this is relevant but when i start a capture i get a lots of warning refering to blank.html like Unknown "user-selec"t property. Declaration abandoned. see that capture ![warning](https://user-images.githubusercontent.com/23210888/33597904-29aec6a2-d9a1-11e7-97c5-72cf86426a8e.png)

**Comment by chenba** [comment]
@iceuponfire Could you try it with a clean profile?

**Comment by iceuponfire** [comment]
I used the profile manager to create a brand new profile and there is no warning anymore but ctrl+c still does not work.

**Comment by chenba** [comment]
@iceuponfire Thanks for all the testing.  Without finding a way to reproduce the bug reliably, it'd be difficult to work on the bug or verify a fix.  🙁

**Comment by stripTM** [comment]
Do you use a different version of Firefox than the en-US lang?

Perhaps it is that in another language the ctrl+c combination is captured for another function.

I'm testing on Firefox Nightly 59.0a1 (2017-12-06) (64-bit) es-ES and it works.

**Comment by iceuponfire** [comment]
I'm french so here is m'y config, using an azerty keyboard. I downloaded the en-US version od nightly and indeed it is working now. So maybe there is something going on with azerty or another locale.

![image](https://user-images.githubusercontent.com/23210888/33760110-eca0157a-dc04-11e7-9d82-a6e8a37828e3.png)

Now it's working i noticed that ctrl+c sometimes does not work at first time, i need to press a second or third time to make it work. It's a bit frustating (no eror message appear on the console). It's completely random, sometimes it work at first time, sometimes not. Anyone else experienced that?
