### ISSUE TITLE
"Made with Firefox Screenshots" doesn't fit

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2683]
Here's what a shot looks like:

![image](https://cloud.githubusercontent.com/assets/44390/25022348/1bc61bda-205b-11e7-9f0a-46dd4238137d.png)

Terrible, amiright?  And it's live!  What are we doing?

I tried just splitting Firefox / Screenshots on two lines, but the alignment is not great:

![image](https://cloud.githubusercontent.com/assets/44390/25022388/3f15c00e-205b-11e7-8c06-0180fe4f4298.png)

**Comment by cecilebertin** [comment]
#2454 
#2530

**Comment by cecilebertin** [comment]
The issue is already described in #2454. There is also a problem with the height in Safari. The button doesn't display on the 100% height. 

<img width="207" alt="screen shot 2017-04-13 at 22 51 25" src="https://cloud.githubusercontent.com/assets/21285660/25034518/ed130c8a-209b-11e7-92b9-3f38d9a0d9a8.png">

I was thinking of using a min-width instead of a fixed width for the button, but I haven't found a solution for the height yet.
See also  #2530.

**Comment by johngruen** [comment]
Hey I fixed the first part of this in: #2685, renaming to deal with @cecilebertin's point about Safari. I'll probably fix this as part of a larger style refactor of the entire shot page UI

**Comment by ckprice** [comment]
I'm going to add this as a `gamma-blocker` per @SoftVision-CosminMuntean's request. /cc @johngruen

**Comment by ckprice** [comment]
It was noted that this is a server bug, but keeping the gamma blocker label on it to emphasis that it should be fixed quickly.
