### ISSUE TITLE
Original page not visible through Page Shot overlay

### ISSUE THREAD

**Issue by akhilman** [mozilla-services/screenshots#2844]
Original page not visible through Page Shot overlay.
![screenshot from 2017-05-16 06-47-33](https://cloud.githubusercontent.com/assets/180812/26084106/caf748c4-3a03-11e7-82b1-993ebd0d2586.png)

**Comment by johngruen** [comment]
@akhilman hey that's no good. So that's an older version of the add-on (we're moving to ship Page Shot natively in Firefox and the Test Pilot add-on is a few versions behind). The newer version is available in Mightly behind an about:config pref if you'd like to test it out (just search for a pref called "Screenshots").

Can you tell me what domain you're on here so i can test it out as well?

**Comment by wresuolc** [comment]
I can't reproduce this on that domain in your screenshot.  Can you try it with a clean profile (or just with fewer add-ons)?  It might be conflicting with something else you have installed.

**Comment by akhilman** [comment]
Do not know what was wrong but after refreshing my profile all works as expected.

**Comment by akhilman** [comment]
This problem caused by custom css that fixes white on white input fields in white on dark gtk themes.
http://forums.fedoraforum.org/showpost.php?p=1703251&postcount=3
