### ISSUE TITLE
Set extensions.screenshots.disabled to false

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2916]
If we set the pref to false (in the Firefox tree) then people can see and change the pref. Now I believe someone would have to create the pref to set it to true.

**Comment by ianb** [comment]
Fixed in [Bug 1369824](https://bugzilla.mozilla.org/show_bug.cgi?id=1369824)

**Comment by ithompson4** [comment]
Firefox Developer Edition 66  Beta 14 Testday -  [testday-20190308] 

Ran into the appended problem 8th March 2019 Testing Firefox Developer for the above referenced Mozilla Testday

It does not appear to matter whether the value of "extensions.screenshots.system-disabled" pref, set it to "false" or "true". For both values the screenshot icon is displayed and active in Firefox Developer.

Raised [Bug 1533743](https://bugzilla.mozilla.org/show_bug.cgi?id=1533743)  in Bugzilla.

If this turns out to be a genuine bug I would like to work on the fix if possible. Thank you.

**Comment by ithompson4** [comment]
If this turns out to be a genuine bug I would like to work on the fix if possible. 

Thank you.
