### ISSUE TITLE
Normalize URL for Sentry

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#2975]
I think because the Background Page URL changes for everyone, the errors aren't getting grouped in Sentry

**Comment by ianb** [comment]
Looking at raven.js some, there doesn't seem to be an easy or supported way to do this.  Maybe after instantiating Raven we can just set `raven._lastHref`.  I don't know if we can set `location.href` and if that would cause any problems – `getLocationHref()` seems to be used several places, and that reads right off `document.location.href`.

**Comment by 6a68** [comment]
This seems like a problem that will definitely affect every webextension that tries to use Sentry.

It [looks like](https://docs.sentry.io/clients/javascript/config/#optional-settings) Sentry does provide a `dataCallback` option, which lets you mutate the data object invoked before the callback. I'll see if we can munge the base URL here. (There's also a `transport` option, but overriding that would force us to do lots more work than we really need to.)

Another option would be to group by Sentry tags, rather than try to group by origin URL.

**Comment by ianb** [comment]
I don't see any option in Sentry to controlling grouping, but I don't know. And duh, my suggestion to modify location.href can't work, that causes a page load.  dataCallback seems like a good thing to try.

**Comment by 6a68** [comment]
re:location.href, worst case, we probably _could_ load raven.js in its own iframe...but that seems awful

**Comment by ianb** [comment]
re:iframe: I think that would be a cure-is-worse-than-the-disease case

**Comment by 6a68** [comment]
Hm, so it turns out normalizing the URL causes Sentry to collect *every* error message into a single line in the dashboard.

Take a look at the https://sentry.prod.mozaws.net/operations/screenshots-addon-stage/ dashboard: a variety of errors have gotten collected into a single line item. UNSHOOTABLE_PAGE gets lumped in with CONNECTION_ERROR.

I'll poke at this a bit more, maybe it's possible to put the error label into the `extra` fields in the `data` object, and sort on that.

**Comment by 6a68** [comment]
I guess I could turn the URL into a totally fake URL of the form `moz-extension://screenshots-addon/$error-type`, it just seems like that might not be the best way to sort events.

**Comment by ianb** [comment]
I'm surprised – with the SDK we had a single stable URL that all errors came from, but the exceptions didn't get over-grouped. Something else must have changed along the way.

**Comment by 6a68** [comment]
Hmm. I'll dig around in the page shot dashboards, then.

**Comment by 6a68** [comment]
Aha. Looks like the "culprit" for page shot is the error message, while for screenshots it's the moz-extension URL.

**Comment by bqbn** [comment]
So according to https://docs.sentry.io/learn/rollups/ and if I read it correctly, because error messages don't have stack traces, they are grouped by exceptions. And because the exceptions don't have either the "type" or "value" attribute, they're grouped by the exception messages themselves, which is "a lot less reliable because of changing error messages".

Maybe add stack traces to, or provide a type or value attribute for the exceptions can help the issue?

**Comment by ianb** [comment]
We have stack traces, though maybe they are in the wrong property. Also since we move exceptions between contexts, and they aren't real exceptions but just objects, maybe Raven isn't recognizing them.

Generally our exception messages are consistent because we've fixed most of the inconsistent messages.

**Comment by ianb** [comment]
Also maybe #2999 would help. We were more careful about stack traces in the SDK version.

**Comment by bqbn** [comment]
When I said "error messages don't have stack traces", I meant the error messages I saw in Sentry web console don't have them. So yeah, maybe you're right that the stack traces are in some place where Sentry can't detect them, thus Sentry isn't able to display them or uses them for grouping purpose.

**Comment by ianb** [comment]
Actually I think you are onto something with the stack traces: we have them, and they all contain random UUIDs ([example](https://github.com/mozilla-services/screenshots/issues/2998)), so if Sentry was grouping on them then it couldn't group anything with a stack trace.

**Comment by 6a68** [comment]
Thanks for the help, @bqbn! I've already been applying a URL normalizing regex to a few fields that contain the `moz-extension://$uuid/$filename` URLs, so it should be trivial to apply that regex globally to a string stack trace. Hopefully that will make grouping Just Work.

**Comment by 6a68** [comment]
Looks like raven doesn't parse stack traces at moz-resource URLs, which explains why we aren't seeing meaningful traces in the dashboard.

Should be easy to fix (by copying https://github.com/getsentry/raven-js/issues/836, which added support for resource URLs), but won't be done by the time we ship. So I'll rewrite moz-extension to just resource.

**Comment by 6a68** [comment]
As soon as I changed the URLs from moz-exception to resource, it looks a whole lot better:

## before
<img width="928" alt="screen shot 2017-06-08 at 11 35 14 am" src="https://user-images.githubusercontent.com/96396/26944861-c6714af0-4c3e-11e7-8bda-c96a0b25952e.png">

## after
<img width="587" alt="screen shot 2017-06-08 at 11 28 35 am" src="https://user-images.githubusercontent.com/96396/26944686-4307e49e-4c3e-11e7-9e5e-4ce62faba455.png">
