### ISSUE TITLE
The screenshot icon causes flickering right after first paint

### ISSUE THREAD

**Issue by fqueze** [mozilla-services/screenshots#3026]
See this video recording of Firefox startup captured on the quantum reference hardware: https://bug1372518.bmoattachments.org/attachment.cgi?id=8877069

At first paint there's no space reserved in the toolbar for the screenshot icon.
Then some empty area appears.
Then this area is expended and the screenshot icon appears in it.
Then the screenshot icon disappears.
Then it's replaced by an icon with a purple star.

Ideally the correct icon should already be displayed at first paint. If that turns out to be impossible, we should at least ensure the right amount of space is reserved at first paint, so that we don't see the location bar and searchbar shifting to the left twice (it actually shifts a third time on this video, but that's either due to Pocket or to the profiler add-on).

If I could file this on bugzilla, it would block the photon-startup bug.

**Comment by johngruen** [comment]
@ianb to describe what's happening

**Comment by ianb** [comment]
Note we also track bugs in a [Bugzilla component](https://bugzilla.mozilla.org/enter_bug.cgi?product=Cloud%20Services&component=Screenshots) (though somewhat less closely than our GitHub issues).

I believe this happens because we delay the WebExtension startup, in an effort to keep Screenshots from affecting overall Firefox performance. The button is itself implemented as part of the WebExtension, and so the space is created when the embedded WebExtension is first started, and the icon appears later due to whatever resource loading process happens as part of the WebExtension system.

I don't have any particular thoughts or suggestions on a fix.

**Comment by wresuolc** [comment]
I filed this at https://bugzilla.mozilla.org/show_bug.cgi?id=1373331
