### ISSUE TITLE
[Enhancement] Add an icon next to the save button to make it more self-evident

### ISSUE THREAD

**Issue by niharikak101** [mozilla-services/screenshots#3056]
From Sharon's UR, the 'my shots' icon hasn't really been clear to participants and 'Save' is often mistaken to mean download. Maybe it would be better to add an icon next to the save button that makes it clearer.

For example, this is the shot preview with the my shots icon:
<img width="558" alt="screen shot 2017-06-22 at 11 57 02" src="https://user-images.githubusercontent.com/16074636/27435459-38195eca-5754-11e7-9955-5e2874a52e84.png">

And something a bit more explicit (ths icon is just a placeholder):
<img width="520" alt="screen shot 2017-06-22 at 12 15 00" src="https://user-images.githubusercontent.com/16074636/27435576-86b8d34e-5754-11e7-85ee-f09f76211810.png">

This also means adding an icon next to the save button in the selection box for consistency.

**Comment by anubhavmax** [comment]
As raised by some of the fellow community members, the "Save" button should provide sufficient information to the users that their screenshots are being saved on Firefox's server, either through the icon or through a notification informing the users before the screenshot is actually saved. This approach would align with Firefox's overall mission of User Privacy.

Further, I personally feel that even though "Save" and "Download" are two strong use cases, the screenshot feature could be made a lot more powerful by providing the user a direct option to copy the image to the clipboard and use it wherever required.

This use case is specifically strong for students, researchers and business users who are consistently involved in browsing the web and creating documents and presentations (A core use case for using screenshot feature for an area of interest rather than the whole screen). The Windows snipping tool has exactly alleviated this problem where the user can select a section of the screen and straight away copy the section to any target document that they might be preparing.

The current user journey for Firefox users in that segment is as follows -
1) Visit Webpage
2) Click Screenshot option
3) Select the section to copy
4) Download/Save the image
5) Visit the download folder
6) Copy or drag the image on to the target document (DOC or PPT)
7) Go back to Firefox to continue work

This user journey involves significant amount of active window shifting between Firefox, Download folder and Target Document as well as file dragging, that adds to user pain points.

A direct "Copy" option would have an user journey as follows -
1) Visit Webpage
2) Click Screenshot option
3) Select the section to copy
4) Click the copy button or Ctrl C
5) Click paste or ctrl V on the target document

This journey involves a single window change from Firefox to Target Document and no file dragging at all. A sample screenshot of how the added functionality might look like is as follows.

![sample](https://user-images.githubusercontent.com/29961407/27933901-170ebb26-6258-11e7-8aa4-01a3e392b451.png)

**Comment by johngruen** [comment]
@anubhavmax that's a pretty great idea

**Comment by johngruen** [comment]
Let me run it by our design team and see if we can't work up some mock ups.

**Comment by johngruen** [comment]
@anubhavmax could you actually file your comment in a separate bug? I'd like to keep this issue to track the original request which i think mitigates the privacy concern @niharikak101 describes. Your bug is a separate feature which i'd like to track on its own to make sure it doesn't get lost.

**Comment by johngruen** [comment]
@chenmorpheus do you think you guys could turn around an _arrow up to cloud_ icon like @niharikak101 suggests here. I'd like to get this patch in soon if possible. I know we discussed changing the string but that will take quite some time unfortunately; I think adding a photon version of the suggested icon would be a good fast mitigation here.

**Comment by anubhavmax** [comment]
@johngruen I have filed it at the following link. 

https://github.com/mozilla-services/screenshots/issues/2582

Let me know if any further information is required from my part.

**Comment by johngruen** [comment]
@Chenmorpheus will provide an asset for this on monday

**Comment by fangshih** [comment]
Just updated the icon to arrow up to cloud. 
https://github.com/mozilla/testpilot-assets/blob/master/Firefox_Screenshots/00_Assets/uploadmyshot.svg
I was wondering should we change the string to upload? 
Or maybe use the arrow down to cloud like this one
https://github.com/mozilla/testpilot-assets/blob/master/Firefox_Screenshots/00_Assets/Savemyshot.svg
As rest of icon in Photon use the arrow down for the save related icon.

**Comment by johngruen** [comment]
Thanks @fangshih let's go with the up arrow for the moment. We can A/B test later. WRT changing the string, i think it's a good idea, but not something we can do right away since it will take time to localize.

**Comment by johngruen** [comment]
hey @fangshih i had to modify the icon a bit to make it clearer at small sizes, but it's looking good!

<img width="498" alt="screen shot 2017-07-10 at 10 30 28 pm" src="https://user-images.githubusercontent.com/3323249/28038528-7b1e2402-65bf-11e7-9704-fbf876af858d.png">

**Comment by SoftVision-PaulOiegas** [comment]
Sorry but I have to reopen this. @johngruen you missed a spot... or two. 😃 
The icon was indeed changed for manual selection, but the old one is still displayed when choosing "Save full page" or "Save visible" options ([screen recording](https://goo.gl/hKqkVT)).

**Comment by johngruen** [comment]
This got uplifted to 10.5
