### ISSUE TITLE
restoring access to screenshots

### ISSUE THREAD

**Issue by newsjunkie247** [mozilla-services/screenshots#3062]
Slightly weird problem: I was having trouble logging into Firefox accounts and through various efforts to try and resolve that I ended up deleting my cookies and disabling sync/removing the weave file. Somehow in the process of that and using different Firefox versions I lost my pageshots but I can see from my web address "history" that they are still online, ie this one: https://pageshot.net/ZrOfvTGqxQS3ZD4D/www.politicopro.com  . Is there anyway to restore that list if the shots are still there with a connection to who created them on the backend somehow? I'm also happy to email with someone more directly about my account information if that helps. I had sync enabled for at least some of the time I was using it but I'm currently having trouble logging in/getting to my account on Firefox 55 and there are other reasons why I am not ready to move to newer Firefox versions yet.

**Comment by wresuolc** [comment]
Thanks for filing this issue.  We're working on integrating with Firefox Accounts which should address this scenario in the future.  However, at this point we are not integrated yet, so any screenshots are based solely on Firefox profile.  I'd suggest you go through your history to grab your links and re-screenshot the screenshots before they expire.

I'm going to close this for now since we're integrating with Firefox Accounts and will address this.  Sorry for the trouble and thanks for using Screenshots.
