### ISSUE TITLE
[Enhancement] Screenshots should work in Firefox Reader Mode

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla-services/screenshots#3092]
[Affected versions]:
- Nightly 56.0a1, Build ID:20170706030206

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Start the latest Nightly build and click the "Screenshots" icon from browser toolbar.
2. Skip the "Tour" pop-up and navigate to https://en.wikipedia.org/wiki/Main_Page.
3. Click the "Enter Reader View" button from the URL bar.
4. Click the "Screenshots" icon from the browser toolbar and observe the behavior.

[Expected result]:
- The Screenshots overlay appears.

[Actual results]:
- "We can't screenshot this page." notification appears.

[Notes]:
- Here is a screen shot with the issue:
![can t take a shot of this](https://user-images.githubusercontent.com/18304511/27920565-af9a2f40-627d-11e7-945a-6bb11859a228.png)
- Browser Console error:
![browser console](https://user-images.githubusercontent.com/18304511/27948428-70c727d4-6302-11e7-8c2e-3dbba36bdd59.png)

**Comment by 6a68** [comment]
This is actually fixed in nightly 62 by https://bugzilla.mozilla.org/show_bug.cgi?id=1466349!

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using the Firefox Screenshots browser version, on latest Nightly build 63.0a1 (2018-07-09). Verified on Windows 10 x64, Mac 10.12.6 and Arch Linux 4.12. However, I've noticed that the "Take a Screenshot" context menu option and the Firefox Screenshots action button are not available.

Moreover, if you install the latest Firefox Screenshots dev version from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), the "Take a Screenshot" option from the "Page Actions" button is greyed out. Possibly related to #4603.
