### ISSUE TITLE
[l10n] seeing the wrong language on dev

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3170]
My Firefox languages are en-US and en, but I"m seeing this on dev:

![](https://screenshots.firefoxusercontent.com/images/2b947a4d-76d1-497a-b258-1a1783d1a378.png)

**Comment by MikkCZ** [comment]
Funny what you see is in Czech. :D Because when I open the dev site with Czech set up in my Nightly, I see https://screenshots.firefox.com/uBCGsIc5aLDDXQjg/screenshots.dev.mozaws.net

It happens for only the three longer description string, which do not have a translation in Czech (just submitted suggestions in Pontoon). I would guess some variables or structures are reused during files processing and do not handle properly, when there is no new value for them in the next language.

**Comment by flodolo** [comment]
Side question: I don't remember changing anything in about:config, but Nightly is pointing me to the dev server instead of production when I use the screenshots button (I have the add-on installed, version 8.2.5313, maybe that's it). That doesn't happen on a clean profile.

Is that a pref that users can change for testing?

**Comment by MikkCZ** [comment]
I think so. about:support shows me version 10.7.0 for screenshots@mozilla.org

**Comment by flodolo** [comment]
Rephrasing question: using the built-in Screenshots, can I point it to the dev-server instead of prod?

**Comment by 6a68** [comment]
> Rephrasing question: using the built-in Screenshots, can I point it to the dev-server instead of prod?

@flodolo No, that's not supported. Did you, by chance, install a test version of screenshots from [the dev site](https://screenshots.dev.mozaws.net/homepage/install-test-local.html) in that profile?

**Comment by 6a68** [comment]
> (I have the add-on installed, version 8.2.5313, maybe that's it).

Ah, yes: having a separate copy of the addon installed would override the built-in system addon.

**Comment by 6a68** [comment]
@clouserw pointed out that this may be a caching issue: first person to see the site caches it for everyone in their particular locale. Investigating.

**Comment by flodolo** [comment]
> @flodolo No, that's not supported. Did you, by chance, install a test version of screenshots from the dev site in that profile?

I probably did. Also good to know that's a potential way to test it…

**Comment by 6a68** [comment]
ETag headers seem to be the culprit here. `express.static` can't be configured to not send ETags, so we'll need to find a way to have per-locale ETag values.

**Comment by 6a68** [comment]
Nope, the bug is in how l10n.js caches the user's locales across requests. Working on a patch now.

**Comment by flodolo** [comment]
(also cc @stasm)
