### ISSUE TITLE
Remove X-Frame-Options or add embedding options that permit framing

### ISSUE THREAD

**Issue by potch** [mozilla-services/screenshots#3200]
Screenshots lend themselves very well to sharing/embedding, but screenshots.firefox.com explicitly bans iframing. Can we add an embedding option (where iframes are permitted for that URI) or relax X-Frame-Options? I don't see anything on the individual screenshot page that is a clickjacking risk.

**Comment by ianb** [comment]
We have Open Graph attributes, and some slightly primitive OEmbed support (though maybe it's broken because of iframe support, I'm not sure! It's hard to tell because OEmbed doesn't seem to be used very much).

Ideally I'd like to look at specific places or use cases for embedding shots, and make sure they work well. Embedding an entire page in an iframe doesn't seem like a great solution for most cases.

**Comment by 6a68** [comment]
@pauljt Any thoughts on safe ways to permit iframe embeds?

@potch Does oembed not get your juices flowing?

**Comment by potch** [comment]
@6a68 not particularly :)

However, the availability of og tags is highly appealing, and may be just what I need.

**Comment by potch** [comment]
@6a68 also looks like oEmbed is 500ing right now? https://screenshots.firefox.com/oembed?url=https%3A%2F%2Fscreenshots.firefox.com%2FWyOLN7FgcmC8CsWB%2Fblog.mozilla.org

**Comment by wresuolc** [comment]
@potch the 500 is fixed.  Does that do what you need?

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
