### ISSUE TITLE
Load locales separately from web page

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3228]
Inlining all the locales into the page adds a lot of content. I think we could precompile all the locales, and include the appropriate one with a script tag. We'd have to wait on that loading before running render.

**Comment by chenba** [comment]
Would like clarification on what "precompile" means here.  Are we generating js that will assign the string representation of a ftl file to a variable (which will be passed into `MessageContext.addMessages`)?

**Comment by ianb** [comment]
There's two approaches, both of which would be reasonable:

- Generate the locale file dynamically (i.e., adding a new route), and make sure it caches well (e.g., `/locales/:lang`)
- Generate the locale files in make-time (e.g., in `/static/locales/language.js`)

As long as the locales are cached well I don't think there will be any substantial difference in performance for dynamically generating them or generating them at compile time.

I *think* the locales for a language use the locales in server.ftl, but substituting in en-US values for any missing keys.

**Comment by chenba** [comment]
I went down the road of generating js locale files at build time and adding the script tags.  But during the process I noticed that since the content is rendered _with the localized messages_ on the server side already, there is no real need to send the l10n messages in the page content.  That is, the messages do not need to be in the `#json-data` script tag.

Please let me know if I misunderstanding this bug.

**Comment by ianb** [comment]
We do render on the server, but we re-render using React afterwards, which makes the page "live". The localization needs to be reapplied during that re-rendering.

**Comment by chenba** [comment]
Created https://github.com/mozilla-services/screenshots/pull/3415 for some initial feedback.
