### ISSUE TITLE
Put Page Action interface in onboarding

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3279]
I'm pretty sure because of Page Action and Library, that our onboarding is out of date.

**Comment by SoftVision-CosminMuntean** [comment]
On Screenshots home page (https://screenshots.firefox.com/), the message and the image from "Get Stared" section still described that Screenshots icon appears in browser toolbar. 
Since the button is moved in "Page Actions" menu, the page should be updated:

![screenshots home page](https://user-images.githubusercontent.com/19226534/30432428-580a4610-996a-11e7-96e4-cdfbab66082c.png)

**Comment by ianb** [comment]
This is fixed in master; from dev site:

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/44390/30440503-5a71cfb4-993c-11e7-9a1b-4b2f8dad6b87.png">
