### ISSUE TITLE
Can we make Page Timings work?

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#3335]
The page timings in GA don't seem to be working I think?  (they are all the same)

@chuckharmston is this something with how we are using GA?  People were talking about a tracking pixel

**Comment by chuckharmston** [comment]
I don't know anything about how Screenshots is using GA, but if you're using the [Measurement Protocol](https://developers.google.com/analytics/devguides/collection/protocol/v1/) instead of the tracking pixel, that could be a cause. You only get what you want to measure, none of the passive stuff you're used to GA using. That's by design, for privacy reasons.

**Comment by ianb** [comment]
We use the measurement protocol on the add-on side, but on the website we use google-analytics.js, which does the comprehensive analytics (e.g., screen size, load times, etc.)

**Comment by wresuolc** [comment]
This kind of seems like a dupe of #3395 or #3673 but those are client side actions and I think this is talking more about loading pages.  If they also fix this, that would be great though.

**Comment by ianb** [comment]
I believe page timings (for web pages) are working now.
