### ISSUE TITLE
Update homepage to reflect 57

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#3444]
Currently the screenshots homepage reflects pre-photon UI for both firefox and Screenshots.

We need to do the following: 

1. If the user is on <= 56 or in a non-ff browser, the UI should remain the same.
2. If the user is on 57 +, we should reveal the currently hidden Full page capture section
3. If the user is on 57 + we should swap the `Get Started` section as follows:
* Title remains the same
* Sentence changes to: Select the Screenshots icon from the page actions menu in the address bar, and the Screenshots menu will appear on top of your browser window.
* Image becomes: https://github.com/mozilla/testpilot-assets/blob/master/Firefox_Screenshots/00_Assets/Landing%20Page/screenshots_image_01.svg

Once 57 formally ships in release, we should change the show/hide logic for here so that non-FF users and 57 users see the same thing.

**Comment by scheinercc** [comment]
Was looking for the screenshots icon (using it since it was in test pilot) and couldn't find it anymore, also not as add-on. When checking the about:newtab on-boarding I landed the screenshots homepage stating the icon should be there. I already checked bugzilla for reports of missing screenshots add-on.
Eventually found this bug ... and the tool ;)

**Comment by truboxl** [comment]
I thought some thing is wrong, everytime I do a new profile cleanup, it doesn't show up in the Customize section. Then it takes me quite some time to find this bug report, so that's where the Screenshot button now at, oh well...
