### ISSUE TITLE
 Please test the docker container in CI

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#3462]
_Copied from https://bugzil.la/1396903_

CI currently tests a server running via directly starting the server. This differs from the way it runs in production, because prod runs the docker container. CI can test the docker container instead, to catch bugs like https://github.com/mozilla-services/screenshots/pull/3458 before they break dev and stage.

**Comment by wresuolc** [comment]
This might have something to do with Node 7 vs 8

Is this going to make our tests run slower?

**Comment by wresuolc** [comment]
The tests are already building the containers, just not running them, so it shouldn't be too much slower.  Instead of building the files and copying them into the container, we'd like to build them inside of the container.  This way ops and contributors could have a stable and reproducible building place.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
