### ISSUE TITLE
Problems with creating screenshot of website in nightly on retina macbook pro

### ISSUE THREAD

**Issue by beingalink** [mozilla-services/screenshots#3479]
Bug originally reported on [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1398215)

User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:57.0) Gecko/20100101 Firefox/57.0
Build ID: 20170908100218

Steps to reproduce:

Load a website that has lots of more content than fits on the screen. On my 2016 Macbook Pro Retina with 13" screen I visited https://niklaslink.de/ and took a screenshot of the complete page using the ... menu in the url bar.

Actual results:

Two issues with the resulting screenshot (see [attachment on bugzilla](https://bugzilla.mozilla.org/attachment.cgi?id=8906018)):
1) The scaling is wrong. The dimensions of the screenshot are too big.
2) The screenshot doesn't include the whole page and is cut off.

Expected results:

The image should have the right dimensions and not being cut off.

**Comment by ianb** [comment]
- The issue with the image being cut off is due to a 5000px limit we have, which we don't actually tell people about. Issue #2129 is to fix this.
- I presume the dimensions are an issue because we are taking the shot at the true resolution (i.e., 2x on a retina screen). That's the intended behavior. We considered not doing this for full page (#3215) but declined. Did you download or save/upload the file? Arguably it's more confusing when downloading, as the image will appear to be the proper size when embedded in the shot web page.

If we had a way to distinguish size from resolution natively in the PNG image that would be great, but I'm not aware of a way (and probably most applications wouldn't pay attention to it).

If I misunderstood please reopen.
