### ISSUE TITLE
Write tests for invalid image files

### ISSUE THREAD

**Issue by g-k** [mozilla-services/screenshots#3482]
Write tests to cover the assertPng invalid-data-url, invalid-data-image, and invalid-data-image-decoded paths.

https://codecov.io/gh/mozilla-services/screenshots/src/a82b616ae48fbab057722efbeab649e765b540a6/server/src/servershot.js#L16

The tests could probably go in a new file in `test/server` and hit the PUT /data/:id/:domain route.

This might be a good starter bug.

**Comment by leni1** [comment]
Hello. Interested in working on this issue. I wanted to know if there's any documentation regarding tests that I should look at before I start e.g. expected test frameworks to use and some sample tests that that the one I'm working on should mirror.

**Comment by g-k** [comment]
Hi @leni1, thanks for taking a look at this!

I'd tackle this by:

1. copying one of the server test python files from https://github.com/mozilla-services/screenshots/tree/93997ed0fb6fed3d9d6ad52329139a1604596b4d/test/server to something like `test_image_validation.py`
2. renaming or deleting the other test functions so only tests for the invalid-data-url, invalid-data-image, and invalid-data-image-decoded cases remain
3. writing tests that POST data that doesn't match the content type
4. checking that the tests cover the above cases by any of the following:

* seeing the server log warnings for those error types
* running the server with `NODE_ENV=dev ENABLE_COVERAGE=1` and checking the local coverage report
* making a PR and checking the codecov.io coverage report

Let me know if you have any questions or get stuck.

**Comment by leni1** [comment]
So looking at the function `assertPng`, I would like to know what `dataUrl` should be. Should I write it as is into the test or there's something else I should use?

**Comment by g-k** [comment]
Good question! In the `assertPngOrJpeg` function the `dataUrl`  follows the https://en.wikipedia.org/wiki/Data_URI_scheme

There are examples in: https://github.com/mozilla-services/screenshots/blob/5bd458345a0613565bc8f0401904582ce50ca55c/bin/load_test_exercise_images.py

I'd recommend using [the test client library](https://github.com/mozilla-services/screenshots/blob/5bd458345a0613565bc8f0401904582ce50ca55c/test/server/clientlib.py) to generate valid images then changing the mimetype or magic bytes in the data url to something invalid.

**Comment by leni1** [comment]
@g-k I have a quick question. As I've been trying to understand the code, I've began to wonder if the Mozilla Screenshots uses plain JavaScript or NodeJS. For example I was trying to understand the line `const PNG_HEADER = Buffer.from(PNG_HEADER_BASE64, "base64");`, in particular what `Buffer` does. A quick search led me to these two resources: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer and https://nodejs.org/api/buffer.html
From the line `const mozlog = require("./logging").mozlog("servershot");` I initially assumed that the `require` was that of NodeJS since the documentation here: https://nodejs.org/api/modules.html#modules_require seemed to match the way it was being used in the code and thus I have been working under the assumption that the docs I should use will mainly be those of NodeJS. Now I'm no longer so sure. Any light you can shed on this would be helpful. Thanks.

**Comment by g-k** [comment]
@leni1 Good question! [The png header line](https://github.com/mozilla-services/screenshots/blob/e4bdf1bb4c3bc088978d2b8b360f720f28c4bcdc/server/src/servershot.js#L14) is a node.js Buffer, so your initial assumption is correct.

Screenshots uses both plain JS and node.js. Generally things in `server/` run on node, `addon/` in vanilla JS, and `shared/` on both.

**Comment by leni1** [comment]
@g-k I was wondering about how to submit the new test file. Should I create a separate branch or fork this repository and then submit a pull request with changes?

**Comment by g-k** [comment]
Hi @leni1, 

> I am wondering how to write the test. Is there a file that handles the user-submitted POST data?  I assumed that I would just have to write a test that mirrors what the function is doing, just that I would be writing the code in Python. That now no longer seems the case to me. I've never written a test for POST data before, so my assumption is that I would have to see how the user sends the POST data we are testing for, then write tests to check its validity.

The POSTed data passes through functions defined in a bunch of files and ends up in [the ServerClip constructor function](https://github.com/mozilla-services/screenshots/blob/8df334e2676bde58644aab9b32654572abbfa255/server/src/servershot.js#L352-L358
), which calls `assertPngOrJpeg`. I think [create_shot](https://github.com/mozilla-services/screenshots/blob/5bd458345a0613565bc8f0401904582ce50ca55c/test/server/clientlib.py#L46
) in the python test client library will hit the right endpoint.

> Should I create a separate branch in my local repository and push the test file or fork this repository and then submit a pull request with changes?

Yep, we're following [this github flow](https://git-scm.com/book/en/v2/GitHub-Contributing-to-a-Project), so:

1. create a local branch e.g. `git checkout -b invalid-image-tests`
1. fork this repo 
1. add your fork as a remote e.g. `git remote add leni1 git@github.com:leni1/screenshots.git`
1. push your branch to your fork e.g. `git checkout invalid-image-tests && git push leni1`
1. make a pull request

Good questions!

**Comment by pradeepgangwar** [comment]
@leni1 can i work on this if you are not working.

**Comment by leni1** [comment]
@pradeepgangwar feel free to submit a patch. Since I haven't submitted a patch as yet, I think you can work on it. If either one of us ends up submitting a patch before the other, then I think the person who submits the first patch should be the "owner" of the issue. At least that's how I've seen it done in other Mozilla projects.

**Comment by g-k** [comment]
Fixed in https://github.com/mozilla-services/screenshots/pull/4298
