### ISSUE TITLE
It's confusing that "Save" means "Upload"

### ISSUE THREAD

**Issue by HappyPony** [mozilla-services/screenshots#3503]
Here https://screenshots.firefox.com/#hello3 is linked the page https://www.mozilla.org/en-US/privacy/firefox/ . Is it correct, that by using of Firefox Screenshots service my screenshots are stored in the Firefox Cloud? I suggest the privacy properties in the ["Firefox Screenshots" README.md](https://github.com/mozilla-services/screenshots/blob/master/README.md) to describe.

#privacy

**Comment by wresuolc** [comment]
If you click the save button it uploads to our servers, but if you click the download button it does not get sent to our servers.

I think the text on your first link is misleading.  We should update this text:

> Save and Share
> 
> When you take a shot, Firefox posts your screenshot to your online Screenshots library and copies the link to your clipboard. We automatically store your screenshot for two weeks, but you can delete shots at any time or change the expiration date to keep them in your library for longer.

**Comment by philipp-sumo** [comment]
this is causing ongoing confusion on various support channels and making us look bad :-(
https://www.reddit.com/r/firefox/comments/7335tz/official_screenshot_description_clarification/

**Comment by 6a68** [comment]
@philipp-sumo We'll get a wording fix landed soon. In the meantime, is there a good SUMO link for confused users who wind up at this github bug?

**Comment by HappyPony** [comment]
What can better SUMO link are, as correct manual in user language here https://screenshots.firefox.com/#hello ? **I suggest this hint** for german user:
> Speichern Sie Ihre zugeschnittenen Bildschirmfotos im Internet, sodass sie leicht zu teilen sind, oder laden Sie sie auf Ihren Computer herunter.

**to change**. While this hint suggest, that I must for save of screenshot local at my device (PC, Tablet, ...) at first upload the screenshot in the cloud.

![111](https://user-images.githubusercontent.com/3226308/31002702-73139da2-a4ec-11e7-98b1-43e7300c3026.png)

In any case, **one hint as popup in browser-language is no goog SUMO link. This hint must for search engines detectable are under one _unique URL_**. S. to it "Multi-regional and multilingual sites" - https://support.google.com/webmasters/answer/182192?hl=en

**Comment by philipp-sumo** [comment]
hi @6a68 , i'm not sure if there's any good link - we just to explain it to people in the meantime: https://support.mozilla.org/en-US/questions/1168009#answer-993488

**Comment by pgerber** [comment]
Calling it *Save* is really confusing, I usually press *Save* before a realize that I clicked the button with the cloud next to it. I appear to use Screenshots too rarely to remember but frequently enough that this has become a serious issue. I'm still hoping #3770 is going to be implemented, preferably with an actual preference in about:preferences and a checkmark during the introduction.

For people that don't want to disable uploading to the cloud, I'd probably be best to rename the button. *Save* traditionally meant storing content on your machine and my guess is that most people still associate it with that traditional meaning. Today it can mean locally or remotely and thus the word is an unwise choice. What we want to tell the user that the content is uploaded to a third party service. Why not just call it **upload** or **share**?

I really hope this gets resolved, I'd be a shame if I had to disable Screenshots permanently.

**Comment by enthus1ast** [comment]
Why not just make a "upload to cloud" button?

**Comment by 6a68** [comment]
@pgerber Hi, #3770 is fixed. The pref is `extensions.screenshots.upload-disabled`, and it is currently available in Nightly. It'll be in release as of version 60. If you want to disable screenshots, the pref is already available in release: `extensions.screenshots.disabled`.

@enthus1ast Thanks for the suggestion. That's a lot of text to fit into a button, especially in languages like German that tend to have longer word lengths than English.

I do think the button label can be confusing for some people, but I'm not sure of the best way to fix it. I'll throw this bug back into triage to see if we can get any product feedback.

**Comment by gerdneuman** [comment]
![image](https://user-images.githubusercontent.com/12525563/37701026-d1cc867c-2ced-11e8-9ff7-8936c98b2fa2.png)

**Please rename "Save" to "Upload", because that's what it does.** I've already hit "Save" a few times accidentically, which uploads the file, when I wanted to save it (locally). What the buttons do here goes against years of user experience. Every application I can think of has a `File > Save` or `File > Save as` dialog and all of these save locally and do not upload.

Citing the [Mozilla Statement, Petition: Facebook and Cambridge Analytica](https://blog.mozilla.org/blog/2018/03/20/mozilla-statement-petition-facebook-cambridge-analytica/):

> At Mozilla, our approach to data is simple: no surprises, and user choice is critical. We believe in that not just because it makes for good products, but because trust is a key factor in keeping the internet healthy.

What is done here goes against this statement and when I read this I (I consider myself a mozillian) found it, well, cynical considering the long-standing complaints here.

From a product perspective I can understand that you want to feed the https://screenshots.firefox.com/ site. I am not arguing that you should change the default primary button. This can still be the Upload. But please rename from `Save` to `Upload` to make clear what it does.

PS Also related: #3603

**Comment by gerdneuman** [comment]
Just to add: This is especially important as I usually do screenshots of sensitive areas / data like server backend or admin pages which are not publically accessible. Because if these were public I would just send a link (URL) and not do a screenshot.

**Comment by neopostmodern** [comment]
How about fixing this today before the whole GDPR thing explodes?

**Comment by rakoczy** [comment]
I don't understand why this is so consequently postponed for so song time. It seems ridiculous the explanation by 6a68 (above, dated Feb 13): "That's a lot of text to fit into a button, especially in languages like German that tend to have longer word lengths than English.", while in another thread [https://github.com/mozilla-services/screenshots/issues/3603](https://github.com/mozilla-services/screenshots/issues/3603)  FatOrangutan commented on Oct 8, 2017:  "I think the following is more intuitive: Local save: floppy disk icon (maybe with an arrow pointing downward) with a tooltip that says "Save" Cloud save: the current icon (cloud + upward arrow) with the button labelled as 'Upload.'" 
Icons are rather easy to interpret and tooltips can contain text of any length, I suppose...

Not long words but unwillingness to fix it once and for all (or perhaps other, less just motives) are the true reason for this never ending story.

**Comment by FatOrangutan** [comment]
I use the following css hack through userContent.css, in case it helps anybody:

```
@-moz-document regexp("moz-extension://[0-9a-z\-]*/blank.html") {
    
    .highlight .highlight-buttons {
        bottom: unset !important;
        background-color: #fbfbfb;
        top: 5px;
        padding: 3px 4px !important;
        border-radius: 3px !important;
        border: 1px solid #dedede;
    }
    
    .highlight .highlight-buttons:not(:hover) {
        opacity: 0.4 !important;
    }
    
    .highlight-button-save,
    .preview-button-save {
        font-size: 0px !important;
    }
    .highlight-button-save::after,
    .preview-button-save::after {
        content: "Upload";
        font-size: 18px !important;
    }
    
}
```

It is better to replace the regex bit with the exact iframe source. You can find it by using (web) inspector on the screenshot overlay. So your final `@-moz-document` rule should look something like `@-moz-document url("moz-extension://6d1dcb20-4749-4f53-3318-2c8ac341dc38/blank.html")`

This css does two things: one, it uses css pseudo selector to rename the `Save` button as `Upload`, and two, it moves the screenshot buttons (close, copy, download, save) from their default position of bottom-outside to the top-inside. This lets you take screenshots of pages with `position:fixed` headers, by simply scrolling to the top, where the buttons are. E.g. screenshots taken of [this page](https://blog.mozilla.org/blog/2018/08/28/lets-be-transparent/):
before:
<details><summary>Before</summary>

![before](https://user-images.githubusercontent.com/8336638/44949915-dd6c0880-ae58-11e8-924c-f7087889124e.jpg)
</details>

<details><summary>After</summary>

![after](https://user-images.githubusercontent.com/8336638/44949916-e2c95300-ae58-11e8-9181-1552cf913bb8.jpg)
</details>

**Comment by muxator** [comment]
Firefox 62 was released two days ago.
The "Upload" button still continues to be called "Save".
![save-button-firefox-screenshot](https://user-images.githubusercontent.com/4067621/45241479-f3604a00-b2ec-11e8-9dd2-13747cbb0726.png)

I consider myself quite an advanced user, yet I was mislead in clicking it at least once. Not fair.
Is there any plan to fix this?

**Comment by chk1** [comment]
On a similar note, the "Download" button should probably be called "Save".  For me, "Download screenshot" implies that a remote server is involved when creating a screenshot although it's done locally in the browser.

**Comment by reidbiztech** [comment]
What kind of a mental midget thought this was a good idea? There is a warning that flashes by so quick it cannot be read and then cannot be brought up again.

This is a real asshole move by someone who has never used a web browser in a professional environment.

First Pocket, then the DNS hijack, now this.

Mozilla is out of control. Please, please, please, listen to the old neckbeards in sandals, not the sjws with blue hair who have no clue.

Seriously considering using Edge now because of this pattern of idiocy. See what you have done? Edge! It's madness I tell you!

Get it together people, and grow the fuck up.

**Comment by muxator** [comment]
If I am not mistaken, this issue is moving on constructively with PR #4963 by @6a68.

**Comment by Deledrius** [comment]
Thank you for mentioning that, @muxator.  The lack of activity here had me thinking otherwise.  I'm very happy to see it being fixed!

**Comment by 6a68** [comment]
Hi everyone. I want to apologize for an inappropriate comment in this bug that I just discovered and removed. This is an unfortunate first for this project.

As a reminder, behavior in any Mozilla space, including this bug, is expected to adhere to our [community guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/). 

I think I can safely speak for the team working on Screenshots when I say that we are thrilled that people use what we've built, and that people care enough about the product to offer comments, file bugs, and contribute code. Keep your input and questions coming, and let's keep on rocking the free web together 🔥🦊

**Comment by enthus1ast** [comment]
@6a68 the form was questionable. But the conclusion was correct.
It is indeed controversial to trick users into uploading screenshots to foreign servers.
For me its also has a negative connotation to delete such comments (even if it reads a little edgy). Did you know what he accidently has shared with mozilla?)

**Comment by 6a68** [comment]
> @6a68 the form was questionable. But the conclusion was correct.
> It is indeed controversial to trick users into uploading screenshots to foreign servers.

Yeah, I could see how you'd feel tricked by that choice of language. I'm glad to be changing it now.

> For me it also has a negative connotation to delete such comments (even if it reads a little edgy). 

:+1: I respect your opinion, and also stand by my decision to remove that comment. Note that none of the other critical comments in this (very long) bug have been censored or removed, because they didn't violate the community guidelines.

To be sure I hadn't overreacted, I talked this over with the rest of the team this morning, including sharing a screenshot of the removed comment, and they agreed it was inappropriate and should have been removed. I'm confident the right action was taken here.

> Or did you know what he accidently has shared with mozilla?

No. Let me be abundantly clear on this point. (1) The user ID is actually just a per-profile random UUID; it can't be guessed. (2) Each shot URL contains a random slug plus the domain the shot was taken from, so it again can't be guessed. (3) If a shot is accidentally uploaded, hitting the delete button will delete it forever, or, if you do nothing, it'll be auto-deleted after 2 weeks. (4) Devs can't access the production databases. Ops has access to do opsy things, like server maintenance, or to delete flagged illegal content. I'm not a lawyer, so you should read our [terms of service](https://www.mozilla.org/en-US/about/legal/terms/services/) and [privacy notice](https://www.mozilla.org/en-US/privacy/firefox/) for the precise details. They are actually fairly readable as such things go.

> 
> edit: To be clear i had nearly the same things in mind as this sleight of hand trick hit me.
> and i also must say that i found it interresting that you see this GDPR thing on every website that even remotely handles customer data, but i don't see anything like this on that Screenshot upload thingy.

I don't know the details, but I do know the legal team reviewed the site well in advance of GDPR taking effect. If you'd like to get the legal details, feel free to open a new bug, and we'll get someone from Mozilla's legal team to weigh in.

> 
> edit2: By following this issues (for longer that i hoped) and the clear unwillingness, that transpires through the lines, to fix this. I came to the conclusion that mozilla does this on purpose.

Nah, we're just a small team with many open bugs, and our quarterly goals tend to focus on adding new features, rather than digging through the backlog.

> 
> edit3: ok ok, to be fair lets see what pr #4963 brings

:+1: Thanks for sharing your concerns. I hope I've addressed some of them.

**Comment by Deledrius** [comment]
The appearance of hypocrisy with this feature when it was released and the lack of clarity on the intent behind the decision has kept me far away from it.  I'm very happy to see this being addressed, and look forward to using it in the future.

> Nah, we're just a small team with many open bugs, and our quarterly goals tend to focus on adding new features, rather than digging through the backlog.
> 

That's unfortunate, especially with an issue like this which can have massive privacy concerns (whether *legally* acceptable or not).  It's sad that growth is not always measured wisely by those at the top.

> > edit3: ok ok, to be fair lets see what pr #4963 brings
> 
> 👍 Thanks for sharing your concerns. I hope I've addressed some of them.

Thank you for taking the time to fix it!

**Comment by muxator** [comment]
**Firefox 66**, official Win x64 package here.

The **"upload" button still reads "save"** for me :(

![Cattura](https://user-images.githubusercontent.com/4067621/54737558-f946ba00-4bb0-11e9-85ba-0ca6538df11c.PNG)
