### ISSUE TITLE
Unable to do anything if the "Never accept third-party cookies" option is set

### ISSUE THREAD

**Issue by cmoud94** [mozilla-services/screenshots#3572]
If I take screenshot and upload it, it shows correctly but I'm unable to delete the shot or change expiration time. It's like that for a while. Also if I want to go to "My Shots" it's searching for a while and then redirects me to tour page.

**Comment by SoftVision-CosminMuntean** [comment]
@cmoud94  thanks for reporting this.
In order to investigate this issue, can you please give us more details? 
On what version of Firefox did you encountered this issue and on what OS? Also, do you have any configuration related to history or cookies? Or you can reproduce it without any changes on a new clean profile?

**Comment by cmoud94** [comment]
I'm using Firefox Nightly (standalone download) on Debian testing.

Here's screenshot of my history/cookies settings.
![screenshot_2017-10-02_12-19-00](https://user-images.githubusercontent.com/3386891/31073398-065ee0fe-a76c-11e7-9b92-b9b3948d188e.png)

Also it's working on clean profile, should've tried it before creating issue, sorry.

**Comment by SoftVision-CosminMuntean** [comment]
Thanks for the screenshots! I have managed to reproduce this issue on Windows, if I set the environment like yours on a new Firefox profile.
After taking a screenshot you can't change the expiration time, the shot name and can't delete the shot. Also, if you navigate to  "My Shots" page you are redirected to the Screenshots tour. 

I have noticed that if you already used Screenshots and then you set the "Never accept third-party cookies" option, the issue is not reproducible. 

Here is a screen recording with the issue:
![screenshots cookies](https://user-images.githubusercontent.com/19226534/31075178-f34a0938-a77c-11e7-8bf9-f3f4952ee1f9.gif)

**Comment by cmoud94** [comment]
Great! I've changed cookies settings from "Never accept" to "Accept from visited" and it's working now.

Thanks for help!

**Comment by wresuolc** [comment]
we'll track this in #3581   thanks
