### ISSUE TITLE
Wrong icon for "Share image"

### ISSUE THREAD

**Issue by rugk** [mozilla-services/screenshots#3578]
On the website you use this symbol for "share link to image":
![grafik](https://user-images.githubusercontent.com/11966684/31097927-4166752c-a7c1-11e7-86a0-c8482102dae9.png)

That icon however means "upload". You should however use this – well known – icon associated with "sharing":
![grafik](https://user-images.githubusercontent.com/11966684/31098049-ada76e6c-a7c1-11e7-9675-772b1810405d.png)

(picture from [Google's material design icons](https://material.io/icons/))

**Comment by ianb** [comment]
Note the current icon is used for sharing on iPhones (though I've never personally seen it on the web). In Firefox we have sometimes used a paper airplane, though I don't believe that icon is used anywhere in Firefox right now.

**Comment by rugk** [comment]
An airplane sounds strange too and IMHO the icon there really indicates upload. An arrow going out of the box to the top -> That is an upload icon. [Look here](https://duckduckgo.com/?q=upload+icon&iax=1&ia=images) and compare [with these](https://duckduckgo.com/?q=share+icon&iar=images&iax=1&ia=images).
The devs should not be influenced by strange design decisions of iOS… (if it is really the case that the icon is used there fore sharing)

**Comment by ianb** [comment]
I'm not a fan of the icon either, just giving some context on it. We'll discuss this at our next team meeting.

**Comment by youwenliang** [comment]
We had the same concern about the sharing icon before but the current design for Screenshots is following what design system provided us. Check out the icon sets here: http://design.firefox.com/icons/viewer/

Might need to consult the design system team to see what they think about this concern.

**Comment by aminalhazwani** [comment]
@youwenliang the share icons is one of most unresolved mystery of design 😅 Every platform seems to follow its own design making it very difficult for web properties to offer a good solution.

A possible solution can be the detection of users's platform in order to serve different share icons based on their OS. There are pros and cons because share icons are very popular on mobile platforms and an Android user might not recognize the Windows share icon on her desktop machine.

Right now the [photon icons website](http://design.firefox.com/icons/viewer/#share) offers two share icons, one for macOS and one for Windows (the windows one is not aligned with the "classic" windows share icon). The 3-dot android share icon is soon to come. 

Let me circle back to the Photon people in order to understand if we have a strategy for the share icon. In case of negative answer this is a good opportunity for defining a new Photon sharing pattern ☺️

**Comment by aminalhazwani** [comment]
@youwenliang I spoke with the Photon people, they are content with the current icon. Also for people who might never encountered this type of icon the current glyph does a good job at delivering the idea of sharing and direction. Thank you for looping us in!

**Comment by johngruen** [comment]
Closing this in favor of #3620

**Comment by 12people** [comment]
@aminalhazwani Microsoft did a widespread A/B test on the subject and found that the best platform-agnostic icon was the right-pointing arrow: https://medium.com/microsoft-design/the-iconography-of-sharing-183a1ad9c6f1 . It's the same metaphor that you use in your Windows share icon.

**Comment by rugk** [comment]
Hmm… the oldschool Windows "link"/desktop shortcut icon. Yeah, this could also be a better icon. In any case better than the "upload" icon used currently…

**Comment by aminalhazwani** [comment]
@12people yes, for windows we have a similar share icon https://design.firefox.com/icons/viewer/#share
