### ISSUE TITLE
Cannot list images on https://screenshots.firefox.com after upgrade to FF 56

### ISSUE THREAD

**Issue by rugk** [mozilla-services/screenshots#3579]
Trying to look for my own icons I go to https://screenshots.firefox.com/shots. It shows me "Searching for screenshots…". Then it reloads one time (appending ?reloaded to the URL) and then it goes to https://screenshots.firefox.com.

No error message, no explanation, nothing… (bad UX, IMHO)

Console output:
```
22:37:36.447 Laden fehlgeschlagen für das <script> mit der Quelle "https://screenshots.firefox.com/ga-activation.js?rev=21.0.0".  screenshots.firefox.com:3
22:37:36.507 Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf data:application/javascript;base64,KGZ1b... blockiert ("script-src https://screenshots.firefox.com https://www.google-analytics.com 'nonce-35e3f52b-0e48-4456-80d3-823ae5af329a'").  (unbekannt)
22:37:36.507 Laden fehlgeschlagen für das <script> mit der Quelle "https://www.google-analytics.com/analytics.js".  screenshots.firefox.com:3
```

I previously used the testpilot addon and there it always worked, but when I upgraded to Firefox 56 it does not work anymore now. 

Maybe related: I use NoScript (of course scripts on https://screenshots.firefox.com are allowed), which previously had an issue breaking webworkers. But they have published a fix, i.e. I can reproduce this issue with v5.1.1.

**Comment by ianb** [comment]
This is typically the behavior when Screenshots does not see you as authenticated. If you look in your cookies (Preferences > Privacy & Security > History > remove individual cookies) do you see cookies for screenshots.firefox.com? The important ones are `user` and `user.sig`.

It looks like the first and third error message say that `ga-activation.js` and `analytics.js` cannot be loaded. The second message indicates the Content-Security-Policy blocked `data:application/javascript;base64,KGZ1b...` – which is probably a script being injected by an add-on (maybe NoScript?) I'm guessing the two analytics files aren't loaded because they are blocked by an add-on as well – some add-on(s) (I can't recall which) block these analytics scripts and then inject a replacement script. That itself should be fine and shouldn't break Screenshots, but it's possible that same add-on is breaking the authentication cookie.

**Comment by rugk** [comment]
I actualy found the issue. I had third-party cookies disabled. (https://github.com/mozilla-services/screenshots/issues/3572)

Anyway that worked with the testpilot extension before. So in https://github.com/mozilla-services/screenshots/issues/3572 you may track the issue itself in order to make it work with that setting.
Maybe use this issue to track the UX issue of "just being redirected without any error message"? Or is that expected this way? (For me, it was quite confusing…)

> It looks like the first and third error message say that ga-activation.js and analytics.js cannot be loaded. 

Yes, that's expected. They are blocked. Anyway, should not you refrain from loading GA when DNT is enabled?

**Comment by ianb** [comment]
OK, we have some other tickets that cover third party cookies, so I'll close this.

We don't send data to Google Analytics when DNT is on, but we still load the scripts. If you are curious you can see the logic in [ga-activation.js](https://screenshots.firefox.com/ga-activation.js)
