### ISSUE TITLE
Make Screenshots work with third party cookies disabled

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3581]
I believe what's causing Screenshots not to work with third-party cookies disabled is that we make all our authentication requests from the background page, and rely on those requests setting the authentication cookie.

The design constraint that led to this is that I didn't want to send the authentication information to a content page. That seemed like it would make it too easy to extract that information with any compromise to the site.

I think by sending the value of the `X-Screenshots-Auth` header to `sitehelper.js` we could do this Well Enough. That header value is basically the value of the cookie (though the cookie is httpOnly, so typically content never gets to see it). It's a value that can't be used quite as easily to authenticate other clients. Then `sitehelper.js` could create an XMLHttpRequest/fetch with that header, and get the cookie set – but it wouldn't appear to be a third-party cookie.

So the basic flow would be:

1. user goes to a page with no authentication (because they've blocked the normal authentication)
2. `wantsauth.js` is loaded
3. wantsauth asks `sitehelper.js` to authentication
4. sitehelper sends the value of X-Screenshots-Auth back to wantsauth
5. wantsauth sends a login request to a new server endpoint with X-Screenshots-Auth
6. the server responds with a response that sets the authentication cookie
7. wantsauth refreshes the page

@g-k @jvehent : feedback from a security perspective?

**Comment by g-k** [comment]
Which pages load `wantsauth.js` and `sitehelper.js`? Are they injected into the page being screenshot, loaded from webextension background or content pages, or from somewhere else?

I think it'd be fine to have auth information on a screenshots.firefox.com content page though ideally not exposed to JS.  It'd be great if we could switch to something first party like a custom header or a samesite cookie to simplify CORS and CSRF protection on the server side.

**Comment by ianb** [comment]
@g-k: right now My Shots and the individual shot pages will load wantsauth.js if the request is not already authenticated. sitehelper.js is the Add-on content worker that is attached to all pages on firefox.screenshots.com.

Currently wantsauth will send an event to sitehelper.js to ask it to log in, and if a login happens then sitehelper.js will send information back to wantsauth (a confirmation that the login happened, and potentially ownership information on shot pages that the logged in user owns, though no actual authentication information nor a deviceId).

The problem here is that the content page has to initiate a request that sets the cookie. Though it occurs to me that maybe sitehelper.js itself can create the XMLHttpRequest and send it, doing so as the content page. Right now that request is coming from the background page, which is why it's treated as a third party cookie. So... I'll have to experiment with that, but it should solve the problem without exposing auth information.

**Comment by agilob** [comment]
related feedback: I just had a problem deleting a screenshot and changing its expiration, console log was reporting 401 unauthorized. Allowing 3rd party cookies and reloading paged fixed it.

**Comment by ianb** [comment]
I started an attempt to fix this in #3601, but it doesn't work :( I can get the request to be made (though to really make it work I have to set the full URL of the XMLHttpRequest on [this line](https://github.com/mozilla-services/screenshots/pull/3601/files#diff-75654d4f875738d0480b58b12b392263R33)), but it still seems to be "coming" from the moz-extension URL. That's the problem we're trying to work around: with third-party cookies disabled, we can't make a request from the add-on code that sets cookies.

@kmaglione: do you happen to have any ideas how to make this work? Our goal is to send this request that will set cookies:

```js
    let MyXMLHttpRequest = document.defaultView.XMLHttpRequest;
    // FIXME: seems impossible to get an XMLHttpRequest that acts as though the
    // content page is what made the request
    console.log("using xmlhttprequest:", MyXMLHttpRequest, XMLHttpRequest === MyXMLHttpRequest);
    let req = new MyXMLHttpRequest();
    req.open("POST", "/api/set-login-cookie");
    for (let name in authHeaders) {
      req.setRequestHeader(name, authHeaders[name]);
    }
    req.send("");
```

But we'd like to avoid sharing `authHeaders` with the content page itself.

**Comment by 6a68** [comment]
@ianb I think we can fix this by either firing the XHR from bootstrap, or by using a hidden window to open a first-party screenshots page.

XPCOM XHR docs are [here](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest#Using_XMLHttpRequest_from_JavaScript_modules_XPCOM_components) and, at least in the console, I can get the XHR constructor without errors. Not sure if e10s will play nice here.

If that doesn't work, the hidden window might. Instead of firing the auth xhr from the background page, send a message to bootstrap, then bootstrap opens a hidden window on screenshots.com, running the auth xhr as a content script in the hidden window's content process. The auth result would be relayed back to bootstrap, then to the background page. The API needed is `Services.appShell.createWindowlessBrowser`, and according to [the docs](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIAppShellService), a content document has to be inserted into that hidden window, then messaging has to be set up manually. Seems painful.

Luckily, it [looks like](https://dxr.mozilla.org/mozilla-central/source/toolkit/components/extensions/ExtensionParent.jsm#871-908) the webextension framework code uses this same `createWindowlessBrowser` API to set up background pages for each webextension. The linked utility method is private, but we can copy the XPCOM boilerplate to get the window + document set up. Not sure about the messaging setup code.

**Comment by 6a68** [comment]
commit `4b57cf9` works for me locally with third-party cookies disabled, nice work. I wasn't aware of the special XHR available to content scripts
