### ISSUE TITLE
Investigate security warnings

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3636]
There's a couple warnings in [this report](https://github.com/mozilla-services/foxsec-results/blob/master/baseline-scan/screenshots.firefox.com/2017-10-13) that I don't understand, and maybe could be fixed (or maybe ignored):

- [ ] Web Browser XSS Protection Not Enabled [10016]
- [ ] Hash Disclosure - MD4 / MD5 [10097]
- [ ] Source Code Disclosure - SQL [10099]
- [ ] Incomplete or No Cache-control and Pragma HTTP Header Set [10015] 
  - On https://screenshots.firefox.com/static/css/home.css?rev=22.0.0 – but why? Cache-Control header seems fine: `Cache-Control: public, max-age=86400`

I understand the rest of the warnings.

The warnings should be in this [zaproxy list](https://github.com/zaproxy/zaproxy/blob/master/src/doc/scanners.md)

**Comment by ianb** [comment]
@g-k do you have any thoughts on these warnings? They aren't that clear to me.

- I believe the XSS protection is referring to [X-XSS-Protection](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection), a header that applies to some other non-Firefox browsers, and maybe isn't important given CSP rules. Also none of the browsers that supports the header has access to any privileged operations in Screenshots.
- I'm not finding much on Hash Disclosure. I'm wondering if it is finding something hash-like and doesn't like that.
- It's possible that Source Code Disclosure is just the github reference? At least I see some other references to looking up repo links

**Comment by g-k** [comment]
@ianb The baseline warnings are generally lower severity and have higher false positive rates especially if they only occur for a few urls like static assets and robots.txt. The [develop branch](https://github.com/zaproxy/zaproxy/blob/develop/src/doc/scanners.md) the list will be more up to date since the baseline runs against the weekly docker build of develop.

* the "Web Browser XSS Protection Not Enabled" is referring to the X-XSS header, which CSP `script-src` supersedes. We do add it to other sites that need to support other browsers or older browsers and it wouldn't hurt to add (I think http observatory checks for it).
* the Hash Disclosure [community script](https://github.com/zaproxy/community-scripts/blob/75433c6253853560fa0eca4ec3fbc26b077b2e4f/passive/Find%20Hashes.js#L29) looks for things that look like password or cryptographic hashes. It's generally pretty noisy and safe to ignore.
  * [docs](https://github.com/zaproxy/zap-extensions/wiki/HelpAddonsPscanrulesAlphaPscanalpha#hash-disclosure) 
* The source code disclosure SQL error is probably from those sites matching one of [these regexes](https://github.com/zaproxy/zap-extensions/blob/b5370f1e85768c0210a1a57ced2938242c563eab/src/org/zaproxy/zap/extension/pscanrulesAlpha/SourceCodeDisclosureScanner.java#L139-L169). It's is also noisy and not generally an issue since we're open source anyway.

**Comment by ianb** [comment]
OK, I'll consider these non-issues then.
