### ISSUE TITLE
Add more share endpoints to Screenshots

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#3685]
Consolidating Requests into One Bug. So far, we've had requests for Imgur and Telegram, but there are definitely other integrations we could consider.

* Imgur: https://github.com/mozilla-services/screenshots/issues/1614
* Telegram: https://github.com/mozilla-services/screenshots/issues/3587

**Comment by Apply55gx** [comment]
I think Whatsapp would also be great since many people use it.

Whatsapp share URL syntax:
[https://stackoverflow.com/questions/21935149/sharing-link-on-whatsapp-from-mobile-website-not-application-for-android#25796908](https://stackoverflow.com/questions/21935149/sharing-link-on-whatsapp-from-mobile-website-not-application-for-android#25796908)

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
