### ISSUE TITLE
Firefox Screenshot outputs empty white image when privacy.resistFingerprinting is enabled

### ISSUE THREAD

**Issue by Paivi-Harkonen** [mozilla-services/screenshots#3691]
Steps to reproduce:

1. Install Nightly.
2. Enable privacy.resistFingerpriting.
3. Go to https://www.mozilla.org/
4. Click on the drop down in the urlbar and choose screenshot.
5. Save your screenshot.

Actual results:

This outputed a white image due to the canvas being blocked by default.

Expected results:

This outputed shouldn't be a white image due to the canvas being blocked by default, maybe there should be a whitelist for the screenshot addon.

-------------------------

https://bugzilla.mozilla.org/show_bug.cgi?id=1412418

**Comment by ianb** [comment]
I've opened [Bug 1412961](https://bugzilla.mozilla.org/show_bug.cgi?id=1412961), which is about privacy.resistFingerprinting, since we can't fix this in Screenshots itself.

We *could* notify people about this bug, and I'll leave the bug open to discuss that option. I don't think we should disable Screenshots (the fingerprinting code is experimental, so IMHO we should let the bugs all hang out), but we could pop up a warning.

**Comment by wresuolc** [comment]
Thanks for filing that bug.  We'll track this there.
