### ISSUE TITLE
Disable screenshot page action on prominent pages

### ISSUE THREAD

**Issue by MikkCZ** [mozilla-services/screenshots#3706]
On AMO, Test Pilot and maybe other pages the screenshot feature does not work (the content scripts are blocked from being loaded). Thus I suggest to disable (`.hide()`) the page actions on those domains.

**Comment by ianb** [comment]
We used to do this, but to check for these pages caused a general performance hit, i.e., even if you weren't using Screenshots everything would be slower because Screenshots was checking if you *could* use Screenshots. 

There's some chance that [Bug 1412377](https://bugzilla.mozilla.org/show_bug.cgi?id=1412377) will help here (moving back to the normal WebExtension pageAction), but otherwise we don't plan to do anything fancier because of the performance issue.

**Comment by MikkCZ** [comment]
I wonder what performance hit can be here. You could just inject a very content script to each and every page loaded and send a message from there to the background script to enable the page action for that particular tab. If the content script cannot be included, it won't send the message and page action won't be enabled. Is this actually slow?

**Comment by ianb** [comment]
The list of blocked sites is small, so it's not hard to just test the URL and see if we should hide Screenshots. But yes, even that is expensive enough that it showed up on the Firefox performance testing.
