### ISSUE TITLE
Add Saved Screenshots to Recent Highlights in the Library

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#3754]
Request from the great @bryanbell.

We should integrate w/ the Library in FF. 

<img width="378" alt="screen shot 2017-11-13 at 7 02 00 pm" src="https://user-images.githubusercontent.com/3323249/32741084-5952893c-c8a5-11e7-9861-2a449cbf3644.png">

I suspect this will be hard.

**Comment by 6a68** [comment]
The simplest way to do this would be to automatically add a My Shots bookmark to the profile. Unfortunately, the bookmark's favicon and title don't match the existing entry in the Library menu:

<img width="350" alt="screen shot 2017-11-13 at 10 23 09 am" src="https://user-images.githubusercontent.com/96396/32742700-136bd7e8-c85f-11e7-962a-7567f6d4cc74.png">

Another issue: looking at the bookmark's entry on the Activity Stream new tab page, the card view of My Shots always shows the sad 'no shots' bear, since the screenshots are generated from an anonymous context:

<img width="327" alt="screen shot 2017-11-13 at 10 43 18 am" src="https://user-images.githubusercontent.com/96396/32742882-919f905a-c85f-11e7-8bfd-0ee3c344c4a9.png">

-----

A bit more detail on how the code seems to work:

Looks like the Recent Highlights UI is filled in using the activity stream new tab code, by calling `NewTabUtils.activityStreamLinks.getHighlights`: https://dxr.mozilla.org/mozilla-central/source/browser/components/customizableui/content/panelUI.js#525

The code for the `getHighlights` function goes something like: fill Recent Highlights with bookmarks, then recent history (excluding bookmarked URLs): https://dxr.mozilla.org/mozilla-central/source/toolkit/modules/NewTabUtils.jsm#1302

**Comment by ianb** [comment]
When I take a screenshot, the page ends up in Recent Highlights. I don't know the exact heuristics, maybe it doesn't happen for everyone or all the time.

It's possible `og:image` or something on My Shots would solve the tile issue. We could even consider a different favicon for My Shots.

**Comment by 6a68** [comment]
I misread the title, thought this was specifically about the 'my shots' page.

I also see this in my Recent Highlights after taking a shot. There are only six spots in the Recent Highlights part of the Library menu, and bookmarks seem to be preferred, so if the user has more than 6 recently visited bookmarked pages, it seems less likely that the shot page will show up.

For individual shot pages, it's more of an activity stream heuristic than anything we can control, I think. For the my shots page, there are some things we could do, mentioned in my first comment.

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
