### ISSUE TITLE
Screenshots - Privacy by Default - GDPR

### ISSUE THREAD

**Issue by HaakonME** [mozilla-services/screenshots#3797]
Screenshots with privacy by default, please - you will need to provide that in the EU because of the GDPR anyway.

How to fix it
* Screenshots without a network connection.
* Screenshot editing without a network connection.
* Save the screenshot locally by default.
* Suggest online saving services - opt-in.
* Remove all cached information about the screenshot after saving.

**Comment by johngruen** [comment]
Elvin will comment on this one

**Comment by wresuolc** [comment]
Thanks for the comment.  We strive for a product that respects privacy, from routing analytics pings through our servers to using randomly generated URLs instead of actual image URLs in them when we do collect URLs.  Breaking down your comment:

>     Screenshots without a network connection.
You already can if you click the download button.

>     Screenshot editing without a network connection.
Editing (annotations) hasn't officially launched yet, but we're working on it.  I think all of these tools live on the website, so they won't be available offline though.

>     Save the screenshot locally by default.
There is no default, you have to choose an option each time.  So, same as your first bullet point, click the download button and it works fine.

>     Suggest online saving services - opt-in.
We don't support any other services other than our own server right now.  If you don't click the 'save' button the image doesn't get sent to them.

>     Remove all cached information about the screenshot after saving.
Is there specific information you're thinking about?  I don't think we save any.
