### ISSUE TITLE
Add "Take a Screenshot" icon to customizable toolbar icons

### ISSUE THREAD

**Issue by gene1wood** [mozilla-services/screenshots#3805]
After getting Firefox 57 I went to take a screenshot and found that the button was no longer in my toolbar or in the extra "Customize" section of the toolbar. After much searching I found in the tour that the screenshot functionality is now in the "..." button in the addressbar.

Would it be possible to add a button to the customizable collection of toolbar buttons to take a screenshot? This would be in addition to where it lives in the "..." menu.

I suspect I'm not the only one who both couldn't find it, and would like to be able to have it in my toolbar as I did before 57 (like in #3487 #3802)

**Comment by wresuolc** [comment]
If you right click on the option in the "..." menu, there is a link to add it to the toolbar.  I'll leave this open for Product recommendations on communicating this better

**Comment by gene1wood** [comment]
> If you right click on the option in the "..." menu, there is a link to add it to the toolbar

Right, I mean being able to add it back to the customizable section of Firefox that contains other add-on buttons and the download icon and the container icon, the place where it was before during test pilot, not to the URL bar where the "..." menu icon is and the bookmark star icon is.

**Comment by alex-mayorga** [comment]
¡Hola!

Ended up here researching for https://support.mozilla.org/questions/1201579

FWIW while adding/removing the button via @wresuolc's hack in quick succession, the doorhanger menu, is that a thing?, ends up detaching itself from the "..." button. Please see https://www.screencast.com/t/etRvd6cT

Hope this gets fixed soon.

¡Gracias!
Alex

**Comment by johngruen** [comment]
Sorry @Gene1wood, closing this. you can ctrl + click the screenshots button in the context menu to pin it.

**Comment by guoyunhe** [comment]
I still want to add it to toolbar instead of address bar. Address bar icons, like Copy Link, Send Link To Devices, Pocket and Bookmark, are actions that handle the URL string. But Screenshot handles the page content. So it fits toolbar better than address bar.

**Comment by antesgeist** [comment]
Any update on this? Was looking for any workound but found nothing so far.

--

I agree with @guoyunhe The screenshot button shouldn't really be coupled with the URL since there seem to be no other relation to it othen than the generated filename when downloaded contains the meta-title of the current page.

I'm not sure of the complexity but I figure it shouldn't be that complicated to fetch the meta-title of the current page (you already control the Browser API) to concatenate to the screenshot if that's the only reason why it is within the URL/page-actions.

Rather, it should be on the browser tools itself so it does makes sense to add it in the customize toolbar panel instead of that page-action dropdown.

Think of it as a "quality of life" improvement. Currently, users and I personally have to first navigate to the page-action menu and find that screenshot button, you can see the pattern here, there are a few hoops though minimal, when done constantly, amounts to some level of compounding effort.

I think the better UX would be if we can just directly click on the "Customize Toolbar Section" Icon of the Screenshot where it is far easier to use than to navigate on the page-action menu.

--

Even better if you could allow further customization by allowing users to pin individual "Tools" from the Developer Tools dropdown. That way, users can have easier access on these selected tools instead of navigating on some menu to find and use them, though that can be something for later.

For now, we'd really appreciate if you guys can decouple the screenshot button from the URL/page-action menu and put it in the Customize Toolbar options instead on future versions.
