### ISSUE TITLE
Pagination appears on empty My Shots page

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3857]
Example:

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/44390/33349201-c8c9acc2-d45e-11e7-9b88-f302bff1ef17.png">

 (Note the `< / 1>` at the bottom)

**Comment by chenba** [comment]
@ianb How do get the page to _stay_ on that view?  Or were you just that quick with the screen capture keyboard combo?

I see that very briefly but then I see:

![image](https://user-images.githubusercontent.com/198055/33396149-4baef954-d50d-11e7-877f-5b96f1f5658e.png)

**Comment by ianb** [comment]
I was quick, yes; it will automatically navigate away after a couple seconds.

**Comment by Softvision-CristinaBadescu** [comment]
I wasn't able to reproduce this issue using Firefox Screenshots 25.0.0 and Firefox Screenshots 26.0.18654, on latest Nightly build 59.0a1 (2017-12-04), on Mac 10.12.6 and Windows 10 x64. I've managed to successfully delete all My Shots and the pagination didn't appear on the empty "My Shots" page, not even for a briefly time.

**Comment by Softvision-CristinaBadescu** [comment]
After further investigations, I've managed to reproduce it using Firefox Screenshots 25.0.0 on latest Nightly build 59.0a1 (2017-12-04) on Windows 10 x64, Mac 10.12.6 and Ubuntu 14.04 x64, by following this steps:

1. Open the Firefox browser.
2. Click the "View history, saved bookmarks and more" menu from the toolbar.
3. Click "Screenshots" and observe the behavior.

This issue is reproducible on clean Firefox profiles, where you have no saved screenshots.

Here is a screen recording of this issue:
![pagination screenshot](https://user-images.githubusercontent.com/31244235/33605982-81fa720c-d9c4-11e7-89f9-2a6191720167.gif)

**Comment by Softvision-CristinaBadescu** [comment]
I've also tested this issue on Firefox Screenshots 26.0.22294, installed from https://screenshots.dev.mozaws.net/homepage/install-test-local.html, and I wasn't able to reproduce it on latest Nighlty build 59.0a1 (2017-12-04), on Windows 10 x64, Mac 10.12.6 and Ubuntu 14.04 x64.
Marking this issue as verified fixed.
