### ISSUE TITLE
Confirm disabled event collection while in Private Browsing

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#3900]
While we don't allow upload, and so we never login to the website and have data collection there, I think we are still collecting events for Private Browsing sessions.

**Comment by wresuolc** [comment]
@6a68 is going to see if PBM already does this for free

**Comment by chenba** [comment]
This is tricky because there's no way to detect if the user is on a private browsing tab from a background script.  `browser.tabs.getCurrent()` always resolve with an `undefined` and `browser.extension.inIncognitoContext` is always false.

`browser.extension.inIncognitoContext` works great in content scripts.

@ianb is there some other API I can use?

**Comment by chenba** [comment]
Actually it's not as bad as it looked.  There's a `tab` object in scope at all the `sendEvent` call sites in `main.js`.
