### ISSUE TITLE
Selection Rectangle Shifted to the Left Upon Clicking on Element

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#3907]
#### STR

1. Ensure your browser window is wide
1. Go to npr.org
1. Start Screenshots
1. Click on one of the stories to select it

#### Expected

Element correctly selected and highlighted

#### Actual 

![image](https://user-images.githubusercontent.com/198055/33776935-903c0330-dc08-11e7-99fb-5e7e88020abc.png)

**Comment by wresuolc** [comment]
possible dupe if we can find the other issue

**Comment by Softvision-CristinaBadescu** [comment]
I've managed to find a similar behavior on https://brightside.me. When you automatically perform a selection you can observe that it is shifted a little bit lower than the preview selection. This issue is reproducible on Firefox Screenshots v28.0.0.0, installed from [here](https://screenshots.stage.mozaws.net/homepage/install-test-local.html), on latest Nightly build 59.0a1 2018-01-05, on Windows 10x64, Mac 10.13 and Arch Linux 4.12.

Here is a screen recording with the issue:
![wrong selection](https://user-images.githubusercontent.com/31244235/34617471-389b4328-f244-11e7-9d59-10de37e609c5.gif)

**Comment by chenba** [comment]
@Softvision-CristinaBadescu I cannot reproduce it on https://brightside.me.  I did notice that you have something open at the bottom of your browser (some sort of counter?).  Could you close that and try it again?

**Comment by Softvision-CristinaBadescu** [comment]
Sure thing @chenba. I've closed Developer Toolbar, retested and still managed to reproduce it again. Moreover, I've managed to reproduce this on latest Firefox release 57.0.4 using Firefox Screenshots 19.2.0.
Here is the screen recording:
![shifted selection rectangle](https://user-images.githubusercontent.com/31244235/34618610-f68fd526-f247-11e7-8ea1-76c52fd8f9e4.gif)

**Comment by chenba** [comment]
@Softvision-CristinaBadescu the reason I wasn't able to reproduce it is that I had uBlock Origin running in that profile. :D

**Comment by chenba** [comment]
This bug doesn't exist on Firefox 57.0.4 (Screenshots 19.2.0).

**Comment by chenba** [comment]
The fix for #3256 is the source of this bug.  (Note: Firefox Send has updated its CSS since #3256 was originally reported.)

**Comment by chenba** [comment]
Note on testing with npr.org: ensure your document width is greater than 1300px.

**Comment by Softvision-CristinaBadescu** [comment]
Hello @chenba! Hmmm, this is strange. I've tested this issue using Firefox Screenshots 19.2.0 on latest Firefox Release 57.0.4 and managed to reproduce it on Windows 10 x64, Mac 10.12.6 and Arch Linux 4.12. 
Here is a screen recording with it:
![shifted selection firefox release](https://user-images.githubusercontent.com/31244235/34664689-c0346fb2-f465-11e7-9b49-ac61d16986fa.gif)

**Comment by chenba** [comment]
@Softvision-CristinaBadescu I am sorry, I should've been more specific.  The shift on x (npr.org) did not exist on the older version of Screenshots, but the shift on y (brightside.me) did.

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible on https://www.npr.org/ using Firefox Screenshots v28.0.0 (installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html)) on Windows 10 x64, Mac 10.12.6 and Arch Linux 4.12.

As for https://brightside.me/, at first look everything seems ok, but I've managed to reproduce this issue by following these steps:

1. Perform an automatically selection.
2. Click "Close" button.
3. Scroll down and perform another automatically selection.

Also, if you don't select "Close" button and scroll the page, this issue is not reproducible.
Moreover, this issue is not reproducible if you don't scroll the page after you clicked the "Close" button and perform another selection.

Here is a screen recording with this issue:
![screenshots - shifted selection rectangle](https://user-images.githubusercontent.com/31244235/34941691-7f1f904a-f9fd-11e7-80ce-28a55998a9c8.gif)

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using Firefox Screenshots 28.0.0 installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on latest Nightly build 59.0a1 (2018-01-16), on Windows 10 x64, Mac 10.12.6 and Arch Linux 4.12.
