### ISSUE TITLE
Ignore the PNG to JPEG Cutoff Limit for Download and Copy to Clipboard

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#3969]
Maybe users are willing to trade some (ok, sometimes a lot of) memory/storage for some speed locally?  Image quality will be better as well.

**Comment by 6a68** [comment]
We could expose this option via a screenshots prefs page or the firefox prefs page

**Comment by nhoizey** [comment]
I was wondering why some of my screenshots are PNG and other JPEG. 😅

What is the cutoff limit?

**Comment by moll** [comment]
Just noticed blurry JPEGs appearing, too. I take it there's no way to hack it to always use PNGs when saving to the local disk without waiting for an official update?

**Comment by moll** [comment]
Found _a_ workaround: Using the Devtools console and `:screenshot --fullpage` saves a PNG where the screenshot button seems to go with JPEG. I assume the cutoff must be less than 1.9MB, the size of a PNG that led me seek out this issue.

**Comment by moll** [comment]
@TheMangoTrain:
> moll: Just to clarify, that workaround is simply to enable the screenshot icon in Developer Tools (which seems to do nothing but fullscreen PNG shots) ?

Full page screenshots, last I tried it. Using the `:screenshot` command you may be able to limit it to particular HTML elements, too.

**Comment by machale** [comment]
@moll 
> Found _a_ workaround: Using the Devtools console and `:screenshot --fullpage` saves a PNG where the screenshot button seems to go with JPEG. I assume the cutoff must be less than 1.9MB, the size of a PNG that led me seek out this issue.
Works great!
> To have the full page PNG screenshot feature as a button, enable `devtools.command-button-screenshot.enabled` in about:config.
Tried this, but can't find the button. Can you point me to the button's location? If it matters, I'm on Firefox 63.0.3 on macOS High Sierra 10.13.6. Thanks.

**Comment by pixelpeeper** [comment]
There should at least be an option for turning off the jpg file size cutoff for local saves and clipboard. It’s managed so far to crap out a handful of screenshots that were not even that large with so much jpg artifacts they are worthless, and this tools way more convenient and practical than doing a full page screenshot in dev tools. Though, thanks for the dev tools workaround!

**Comment by ianb** [comment]
This was implemented

**Comment by TNW9imKLC3fv** [comment]
I found this thread via https://github.com/mozilla-services/screenshots/issues/4860 from one of the top results on Duckduckgo search for firefox screenshot png:

This is definitely not implemented, just tried to save a 1080x1080 (right click > take a screenshot > save visible > Download button on the popup (no uploading/saving to mozilla's servers needed) and it still only has JPG as an option


I checked and even with MS Paint's wonky PNG handling compared to Imagemagick, resaving with it still comes out as only 2.6MB, that's really not much these days at all, Twitter's autoplaying 2m20s mini-videos are bigger and again this is going straight to disk drive so no worries about bandwidth (probably actually a little larger due to the PNG having to save the additional changed pixels from the additional noise/artifacts created by the double JPG encoding of images on the screenshot of the page that've already been JPG-mangled https://en.wikipedia.org/wiki/File:Comparison_of_JPEG_and_PNG.png )

Since screenshots often will already have JPGs on the page, re-encoding adds even more noise/artifacts which contributes to an overall decline of quality of shared images on the internet when you consider that in some cases the only surviving copy of an image for The Internet Archive's Wayback Machine might be a screenshot someone takes (sites like twitter doing the same, tumblr permanantly reducing images to max 1280x size, facebook, pinterest etc, are actively vandalizing by doing this, when in some cases the original work from an artist or photographer etc won't make it online (RIP @alinap0pa)

**Comment by TNW9imKLC3fv** [comment]
I found this thread via https://github.com/mozilla-services/screenshots/issues/4860 from one of the top results on Duckduckgo search for firefox screenshot png:

@ianb This is definitely not implemented, just tried to save a 1080x1080 (right click > take a screenshot > save visible > Download button on the popup (no uploading/saving to mozilla's servers needed) and it still only has JPG as an option


I checked and even with MS Paint's wonky PNG handling compared to Imagemagick, resaving with it still comes out as only 2.6MB, that's really not much these days at all, Twitter's autoplaying 2m20s mini-videos are bigger and again this is going straight to disk drive so no worries about bandwidth (probably actually a little larger due to the PNG having to save the additional changed pixels from the additional noise/artifacts created by the double JPG encoding of images on the screenshot of the page that've already been JPG-mangled https://en.wikipedia.org/wiki/File:Comparison_of_JPEG_and_PNG.png )

Since screenshots often will already have JPGs on the page, re-encoding adds even more noise/artifacts which contributes to an overall decline of quality of shared images on the internet when you consider that in some cases the only surviving copy of an image for The Internet Archive's Wayback Machine might be a screenshot someone takes (sites like twitter doing the same, tumblr permanantly reducing images to max 1280x size, facebook, pinterest etc, are actively vandalizing by doing this, when in some cases the original work from an artist or photographer etc won't make it online (RIP @alinap0pa)

**Comment by brudolp** [comment]
should this issue be reopened or can I file a new one?

**Comment by Frederick888** [comment]
@ianb So what's the correct way to get a PNG screenshot without using developer console now?

**Comment by stephanethomas** [comment]
@ianb, @chenba: I'm still having Firefox Quantum 66.0.5 saving images as JPG instead of PNG (using the button). Are you sure it's implemented? What's the corresponding pull request?

**Comment by chenba** [comment]
@stephanethomas I don't think this was implemented.  Perhaps Ian was thinking of the image dimension limits for download/copy there were removed.

**Comment by Exagone313** [comment]
Only the screenshot feature from dev tools save in PNG, but sometimes it doesn't save a screenshot at all, I even found a website that detects when you open dev tools and switch to another page (other bugs).

**Comment by mistydemeo** [comment]
Since it doesn't look like this was implemented, can this issue be reopened? Or should I open a new issue?

**Comment by Darkmaster006** [comment]
I would love to have this too. I need to crop parts of a website (which, mind you, don't amount to more than 2 MB per screenshot) and when I click on 'Download' it gets them in JPEG for some reason? I'm not sure if copying and pasting on Paint and then saving it in PNG does anything, but it's a hassle when I could just download. Hope this can be solved quickly. Allowing for options is always good.
