### ISSUE TITLE
Investigate slow Step One times after Jan 10th

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#4036]
On January 10th the first step of taking a screenshot went from <1s to several seconds to execute.  Any ideas on what happened?

![image](https://user-images.githubusercontent.com/16946141/35462620-922e55b6-02a1-11e8-899d-e6898cf02da2.png)

**Comment by chenba** [comment]
Looks like a lot of it is from the context menu.  And looking at the distribution, there are 3600+ sec (over six _minutes_) data samples.  That kind of extreme numbers can really screw up an average.  No idea what could've caused it though.

![image](https://screenshotscdn.firefoxusercontent.com/images/53e0554c-c2c9-410f-bb56-c07836548d6f.png)

**Comment by wresuolc** [comment]
That is a crazy spike, but yours goes back down after that day and mine doesn't which is odd.  Maybe my query is bad.

My graph shows a percentile to avoid getting washed out by a bad average (the red & yellow lines)

**Comment by SoftVision-CosminMuntean** [comment]
I just finished to compare the time until the Screenshots overlay is displayed, if it's activated from context menu, between Firefox 57.0.4 and Firefox 58.0.1 release.
Overall, there is not a big difference between the Firefox versions. The Screenshots overlay is displayed in less than a second. But, randomly on Firefox 58.0.1 Screenshots overlay is displayed in 1 second or a second and a half on large pages.  
The most noticeable lag I have observed is on a IMac (Early 2009) with 10.13 OS version.  The overlay it's displayed after ~2 seconds on Firefox 57.0.4 and on Firefox 58.0.1, after ~3 seconds.
So probably on lower machines there is a noticeable lag until the overlay it's displayed, but it's not a big difference between Firefox 57.0.4 and Firefox 58.0.1.

In order to test this I have used the following websites: cnn.com, imgur.com, twitch.tv and wikipedia.org. Also, tested on multiple OS'es: Windows 10 x64, Windows 7 x64, Windows 7 x32, Ubuntu 16.04, Mac Book Pro 10.12 and IMac 10.13.

If you guys know a tool that can automatically measure the time when the overlay is displayed, I can do more testing.

**Comment by 6a68** [comment]
@SoftVision-CosminMuntean Thanks for your very thorough investigation. I think we can rule out any upstream changes in 58 as a root cause for these timing bugs :+1:

**Comment by wresuolc** [comment]
I dug into this a bit more via BigQuery.  It looks like most interactions with us make 10-20 pings to GA.  As few as 5 if they've already gone through the introduction.  

A key takeaway for me here is that we sent the events and then we send the timing for the events in a separate ping.  This leads to some inconsistencies.  I've grabbed some random scenarios below (all of these are on Screenshots 25.0.0):

Scenario 1:
- At time 0 they `start-shot` via the context menu
- At time 328 they are prompted with the first introduction slide
- At time 99606 they hit Esc to cancel the slides
- At time 100163 the timing ping for start-shot hits the server with a value of 100245
- At time 101183 they hit Esc and cancel the whole shot

Scenario 2:
- This person had a total of 87 hits so I'm not going to detail them all here, but stuff that stands out:
  - Time 0 they 'start-shot' via the context menu
  - After they went through the full set of slides and clicked 'done' the timing ping fired with a value of 22k or so
  - Their first shot failed to register (401 response) and the upload failed.  It worked on the 2nd try.
  - They went on to make several shots via start-shot on the context menu.  None of the other ones had a long delay.
  - They also did much resizing and dragging

So... it could be just the reporting is messed up, and people aren't actually waiting around for seconds/minutes/days for the interface to appear.  I guess the question is...why wouldn't a ping fire right away?

**Comment by 6a68** [comment]
Ah, of course. I'm not handling the case where onboarding is shown.

**Comment by 6a68** [comment]
Still doesn't explain why the delays are only seen in the context-menu case, though...

**Comment by chenba** [comment]
I don't think it was only, but majority was from the context menu.  People accidentally discovering Screenshots on the context menu?

**Comment by 6a68** [comment]
Good call, it is probably a lot easier to stumble over screenshots via the context menu than via the page action menu.
