### ISSUE TITLE
Cannot draw box for screenshot with touch in Nightly on Linux

### ISSUE THREAD

**Issue by rugk** [mozilla-services/screenshots#4057]
Using Nightly 60.0a1 when I try to use Firefox Screenshots, I can only *tap* somewhere to select an element.

**What should happen:** When I drag (tap) and drop (move and release finger) I expect this to create a box for selecting the screenshot.

**What happens instead:** It scrolls the website in the background.

Fedora 27 x64
GNOME, **Wayland**
[Flatpak version](https://firefox-flatpak.mojefedora.cz/)

**Comment by SoftVision-CosminMuntean** [comment]
I haven't managed to install the unofficial Nightly flatpak build due to some errors, but I tested this issue using an official Nightly (60.0a1) build downloaded from [here](https://ftp.mozilla.org/pub/firefox/nightly/2018/02/2018-02-03-22-03-31-mozilla-central/firefox-60.0a1.en-US.linux-x86_64.tar.bz2) and the issue is not reproducible. Tested on Fedora 27 x64.

@rugk can you please retest this issue using the [official Nightly build](https://ftp.mozilla.org/pub/firefox/nightly/2018/02/2018-02-03-22-03-31-mozilla-central/firefox-60.0a1.en-US.linux-x86_64.tar.bz2) to see if you can still reproduce it?

**Comment by SoftVision-CosminMuntean** [comment]
I think I misunderstood the issue. 
@rugk you cannot perform a selection using the touchpad or on a touch screen display? If you cannot perform a selection on a touch screen displayed, I think this issue is similar with #2888.

**Comment by rugk** [comment]
Touch screen, yes.

So closing this as a dupe of https://github.com/mozilla-services/screenshots/issues/4057.
