### ISSUE TITLE
Screenshots does not work on Simply Recipes

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#4148]
Try shooting this: https://www.simplyrecipes.com/recipes/minestrone_soup/

The iframe does not load.

**Comment by SoftVision-CosminMuntean** [comment]
This issue is no longer reproducible using Firefox Screenshots v31.3.0 dev installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html).
Tested on latest Nightly build 61.0a1 (2018-03-25), on Windows 10 x64, Mac 10.12.6 and Arch Linux 4.12.

But, I have noticed another issue regarding this page. It seems that after saving a shot, the saved shot link is not copied to the clipboard and a "Clipboard copy failed" error message is displayed.
I have logged this issue in #4269
