### ISSUE TITLE
Screenshots doesn't account for DPI scaling anymore

### ISSUE THREAD

**Issue by FatOrangutan** [mozilla-services/screenshots#4174]
STR:

1. Have dpi scale >100%
2. Take a screenshot using either the drag / click method or the 'Save full page' button. Download it somewhere.

AR:

1. screenshot turns out to be tinier than what you had on screen
2. You now need to zoom in in your image viewer to make things readable but also blurry in the process

ER: it should be the same size, like it used to be until recently

The 'Save visible' button does still respect DPI. Issue seems to be with only drag, select and the 'Save full page' button.

I'm on Nightly 60.0a1 (2018-03-03), Screenshots v30; Windows 10.

**Comment by SoftVision-CosminMuntean** [comment]
I have managed to reproduce this issue on the latest Nightly (60.0a1) build using Screenshots 30.0.0 version on Windows 7 x64 with a 150% DPI scale set. It seems that the issue is not reproducible on older Nightly builds with Screenshots 29.0.0 version. So think that the issue is a Screenshots regression and it was introduced on the latest (30.0.0) version.

I was able to reproduce the issue for a small downloaded image:

- Screenshots 30.0.0 version (reproducible):
<img width="960" alt="bad" src="https://user-images.githubusercontent.com/19226534/36969443-2c9d1ada-206e-11e8-83d4-a63fd9fe6012.png">

- Screenshots 29.0.0 version (not reproducible):
<img width="960" alt="good" src="https://user-images.githubusercontent.com/19226534/36969447-2f3f3fd4-206e-11e8-8ed8-9b1e61b594cd.png">

**Comment by 6a68** [comment]
This bug affects all downloaded or copied images.

Full page images have always been low-resolution, whether uploaded, downloaded, or copied. I'll file a followup bug to reconsider going full-resolution when downloading / copying.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue using latest Screenshots (31.2.0) dev version and the issue is no longer reproducible. Tested on:
Windows 7 x64 with DPI scale set to 125%, 150%;
Windows 10 x64 with DPI scale set to 150%, 200% and 300% (on a 4k monitor). 
Mac 10.12 with DPI scale set to 150%
