### ISSUE TITLE
Sometimes downloading a screenshot doesn't save with a .png extension

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/screenshots#4201]
This was reported at https://discourse.mozilla.org/t/no-extension-on-saved-screenshots/26213/3

When they click 'download' they are prompted for a name and the pre-filled name doesn't always include a .png.  @SoftVision-CosminMuntean have you seen this before?

**Comment by SoftVision-CosminMuntean** [comment]
I haven't encountered this issue until now. Also, I tested this on the latest Firefox (58.0.2) release and latest Nightly (60.0a1) build with all the add-ons that the user described, but I haven't managed to reproduce the issue. Tested on Windows 7 x64.

However, I will ask the reporter on Discourse for more information.

**Comment by chenba** [comment]
The Discourse thread mentions _editing_ the filename as well, so we should clarify that this bug is _not_ about that.  You can see in the original reporter's screen capture of the Save As dialog that the file type is set to All Files.  That's why when he edited the filename, Windows does not automatically append a file extension.  (It's not a web download so there's no content-type header to inform the browser; maybe Firefox should perform some detection with given filename though?)

**Comment by wresuolc** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1446798

**Comment by chenba** [comment]
Another bug filed here: https://bugzilla.mozilla.org/show_bug.cgi?id=1424502

**Comment by chenba** [comment]
[Bug 1396280](https://bugzilla.mozilla.org/show_bug.cgi?id=1396280) is the relevant upstream bug.  It is P5 though.

**Comment by chenba** [comment]
I think we should close this issue.

**Comment by 6a68** [comment]
I concur. Let's close!
