### ISSUE TITLE
Misleading information : "This image has been croped to 10000px."

### ISSUE THREAD

**Issue by Totogro** [mozilla-services/screenshots#4205]
On my very first try of this functionality, I took a screenshot of this long page : https://github.com/mozilla-services/screenshots/blob/master/docs/METRICS.md
When I was shown the small preview of the screenshot and asked to choose "copy to clipboard" / "download to my computer" / "upload to the cloud", there was this information at the bottom of the screen : "This image has been croped to 10000px."

I was disappointed to see that Firefox screenshots could not save an image more than 10000px long.
Then, on checking the downloaded image, it appeared complete, and the height was 13208px.
The screenshot preview had been croped, not the proper image I wanted to obtain.
The problem was not with the functionality, but simply a misleading warning message that made me think the functionality was arbitrarily limited to 10000px long screenshots.

This information message should be changed to "This preview image has been croped to 10000px." in order not to be misleading for the first time / casual user.

**Comment by chenba** [comment]
@Totogro Thanks for the feedback.

The confusion (and unintentionally misleading message) arise from the fact that the current 10000px limit applies to the "Save" functionality, but not copy to clipboard or download.  So we'll need a message or messages to inform the users when the limit applies and what they see in the preview is what they (don't) get.

**Comment by johngruen** [comment]
@chenba let's do this:

1. The preview should show the entire height of the image.
2. The crop message show be displayed between the button list and the  preview image, but it should only be shown if the user hovers over the save button. 

If you can make a PR that does this, i can follow up with some style polish. 

Thanks for filing @Totogro

**Comment by Lewiscowles1986** [comment]
URL to test on http://www.aims360.com/value/benefits/

**Comment by Lewiscowles1986** [comment]
How to build this plugin? 

https://github.com/mozilla-services/screenshots/blob/328696fb42e66fe4a6fdc13dd9e68aa4ca246692/addon/webextension/buildSettings.js.template#L7

It looks like this is where the limit has come from.

**Comment by chenba** [comment]
@Lewiscowles1986 Take a look at the [README](https://github.com/mozilla-services/screenshots/blob/master/README.md) on how to set up the project.  Then running `make bootstrap_zip` will make you an unsigned addon you can load through `about:debugging`.  You do need Nightly or Developer Edition in order to use unsigned addons.

**Comment by chenba** [comment]
> The crop message show be displayed between the button list and the preview image, but it should only be shown if the user hovers over the save button.

@johngruen The layout looks weird when there's a gap between the buttons and the preview image.  How about we put the message on top of the image?

![image](https://user-images.githubusercontent.com/198055/40455758-f4d14a5c-5eb3-11e8-8da4-0caa256b24e0.png)
vs.
![image](https://user-images.githubusercontent.com/198055/40455824-39f1abc2-5eb4-11e8-818c-064273e73112.png)

**Comment by johngruen** [comment]
@chenba wfm

**Comment by chenba** [comment]
@johngruen, @sevaan If the message is placed immediately below the row of buttons on hover, it looks a little busy, especially with the button tooltip (the screen capture didn't capture the mouse cursor).  But since the user's focus is already on the Save button, I don't think the message should pop up far away from it.  Also, that message text is a placeholder; I'm taking suggestions. 😁 

Let me know what adjustments you want me to make.

![image](https://user-images.githubusercontent.com/198055/41747424-9a121f20-7573-11e8-8e10-1e349a387034.png)

**Comment by sevaan** [comment]
As for text, I spoke to Meridel from Content Strat and she says:

> Saved image will be cropped to 10,000px in height.

**Comment by 6a68** [comment]
@sevaan The fix for this issue just landed. Feel free to open a followup bug if UX / CSS tweaks are needed. Closing.
