### ISSUE TITLE
I cannot use/enable Screenshots feature

### ISSUE THREAD

**Issue by paldys** [mozilla-services/screenshots#4220]
I cannot see it, when I click on the three dots in the location bar: https://postimg.org/image/59fqo4pfx/ 
I cannot see it, if I right click somewhere on the page: https://postimg.org/image/dexsmbvp9/ 

I use 59.0 version on Win 7.

I have tried to enable/disable it in about:config, option extensions.screenshots.disabled (and restart the browser), it doesn't help.

p.s.: It might be not related, but who knows: I am unsure, if in the same browser, but I have probably tried it in test pilot, but then I removed it.

**Comment by SoftVision-CosminMuntean** [comment]
@paldys Thanks for reporting this.

The "extensions.screenshots.disabled" Boolean pref should be set to "false" in order to have Screenshots enabled.
Can you please navigate to "about:addons" page and verify if in the "Extensions" section you have Screenshots add-on or Page Shot available? If yes, can you please remove it and check again if Screenshots it's available in your browser?

Also, before updating to Firefox 59.0 release, did you have Screenshots enabled on Firefox 58.0.2?

**Comment by paldys** [comment]
The "extensions.screenshots.disabled" Boolean pref is set to "false".
I cannot see it on addons page. Can I reinstall it somehow?

I believe this is not related to version number. As of my understanding it should have been part of Firefox from a specific version, but I have never seen the feature in my browser.

**Comment by SoftVision-CosminMuntean** [comment]
Yes, Screenshots should be available since Firefox 57 release.  Probably some prefs are in conflict since you had Page Shot installed.
But, in order to investigate this, can you please provide the "about:support" page? In order to do this navigate to "about:support" page, click the "Copy raw data to clipboard" button and paste the copied text into a text editor and attach the file here.

**Comment by paldys** [comment]
Here you go:
[rawdata.txt](https://github.com/mozilla-services/screenshots/files/1810964/rawdata.txt)

**Comment by SoftVision-CosminMuntean** [comment]
Thanks @paldys!
It's weird, Firefox Screenshots is listed in "Firefox Features" section but is not available in the browser.   Can you please test this in Safe Mode or with a new Firefox profile and see if Screenshots is working? Here is a tutorial for creating a new profile: https://goo.gl/ZwTdhp

**Comment by paldys** [comment]
Safe Mode didn't help. Creating a new Firefox profile did help.

**Comment by paldys** [comment]
Well... that worked... I should have read what in does in the first place... So now, all my settings, all my extensions and all my container settings are gone... I could have just used the new profile and I could have set it up for myself too.

Anyway, now I see the Screenshots, thanks for the help. :+1:
