### ISSUE TITLE
Document how shot deletion works

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/screenshots#4307]
(Re: conversation in Slack yesterday)

We could just do this in the SUMO page; you can add a comment to this bug (which I need to follow up on anyway): https://bugzilla.mozilla.org/show_bug.cgi?id=1444120

**Comment by wresuolc** [comment]
- Deleting removes the image immediately
- Expiring has a 2 weeks grace period where it doesn't get deleted yet (the author can restore it)
- title/domain are retained permanently in case someone visits the old page

**Comment by wresuolc** [comment]
Moving back to Sprint because I will lose this if its in Stretch.  Any feedback on my proposal:

**What happens when a shot expires?**

By default, screenshots saved online will expire.  After they expire the page to view the shot:

* Will no longer display the shot but will show the domain the shot was taken at
* If you took the shot and visit the page within two weeks of its expiration you will see an option on the page to restore the image.  After two weeks the image will be permanently deleted.

**Comment by wresuolc** [comment]
Answer added to https://bugzilla.mozilla.org/show_bug.cgi?id=1444120#c8
