### ISSUE TITLE
Firefox Screenshots dev version can not be installed from the website

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla-services/screenshots#4352]
[Affected versions]:
- Nightly 61.0a1
- Screenshots 32.0.0 dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and navigate to https://screenshots.dev.mozaws.net/homepage/install-test-local.html.
2. Click the "Install" button.
3. Click the "Allow" and afterwards the "Install" button.
4. Observe the behavior.

[Expected result]:
- Firefox Screenshots dev version is installed.

[Actual results]:
- "The add-on could not be downloaded because of a connection failure" error message is displayed.

[Notes]:
- This issue is not reproducible if you use a custom build cloned from the latest master.
- Here is the error displayed in browser console:
![ss - can not install ss](https://user-images.githubusercontent.com/31244235/39116882-35bfbbd0-46ee-11e8-8f60-012ba2d4fad8.png)

- Here is a screen recording with the issue:
![ss - cannot install firefox screenshots dev version](https://user-images.githubusercontent.com/31244235/39116894-3d7eae6c-46ee-11e8-8b76-4335a1465c4d.gif)

**Comment by chenba** [comment]
Seems to be working now.

**Comment by chenba** [comment]
This is happening to me now.  I think the difference is that I updated to the latest Nightly.

**Comment by chenba** [comment]
...and the bug has gone away in the latest Nightly.  I've verified in Windows 10 and Linux.

**Comment by Softvision-CristinaBadescu** [comment]
I've noticed that eventually I can install the latest Firefox Screenshots dev version only after I restart the browser and re-install it, on latest Nightly build 61.0a1 (2018-04-24).

**Comment by SoftVision-CiprianMuresan** [comment]
I think I've gotten to the bottom of this issue. We have 3 scenarios which reproduce this:

1. Create a new profile, set the prefs and trying to install the add-on from the webpage will result in the connection error message. After restarting the browser the add-on can be installed successfully.
2. Dismiss the dropdown when prompted to either install or cancel the install. Try to install the add-on from the page again and the add-on can't be installed until the browser is restarted (see 1.)
3. Remove the add-on from the about:addons page, and try to install from the webpage. The add-on can no longer be installed until the browser is restarted.

This issue is not reproducible with Nightly builds from 2018-04-01 to 2018-04-15.  I've tried to find a regression range but it resulted in 3 different pushlogs from two different machines, so I've ruled them out as inconsistent.

**Comment by SoftVision-CosminMuntean** [comment]
I have noticed that if you manually add the "extensions.install.requireBuiltInCerts" boolean pref and set it to "false" the issue is not reproducible and the Screenshtos dev is correctly installed.
@sevaan can you please add the pref and see if the issue is still reproducible?

I had a similar issue on Test Pilot. I haven't managed to install the add-on because the pref was not set.

**Comment by sevaan** [comment]
Hey @SoftVision-CosminMuntean that worked! I was able to install the Add-on without any errors.
