### ISSUE TITLE
[Annotations] The tooltip is not displayed for the edit button if the badge is hovered

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla-services/screenshots#4410]
[Notes]:
- If you don't hover the badge, only the tooltip is displayed, but the background is not highlighted.

[Affected versions]:
- Firefox 60.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Firefox Screenshots has never been used before.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Click the "Page actions" button and select "Take a Screenshot" option.
3. Save the image.
4. Hover the "Edit this image" button's badge and observe the behavior.

[Expected result]:
- The button is highlighted on a darker background and the "Edit this image" tooltip is displayed.

[Actual results]:
- The tooltip is not displayed.

[Additional notes]:
- This issue is not reproducible if the edit button does not have its badge.
- Here is a screen recording with the issue:
![ss- edit button](https://user-images.githubusercontent.com/31244235/39861698-0f212806-544a-11e8-8425-90e5fd1317cf.gif)

**Comment by ShivangiKakkar** [comment]
@Softvision-CristinaBadescu @wresuolc Hey! I am new to contributions here. I would like to work on this issue.

**Comment by clouserw** [comment]
hi @ShivangiKakkar .  you're welcome to it :)  @punamdahiya or @chenba are good people to talk to if you need help.  Cheers

**Comment by punamdahiya** [comment]
@ShivangiKakkar welcome! this issue was logged in May, since then edit button code was touched to add a promo dialog in issue #4724 and might have fixed this. 
@Softvision-CristinaBadescu  Can you please help verify if this issue still exist. @ShivangiKakkar In the mean time please feel free to pick a issue from [good first issues](https://github.com/mozilla-services/screenshots/labels/good%20first%20issue) , #4312 is another good one to start with.

**Comment by ShivangiKakkar** [comment]
@punamdahiya  Thanks a lot :)

**Comment by punamdahiya** [comment]
@ShivangiKakkar And reading STR closely (step 4) , found this issue exists You are welcome to work on this and feel free to reach out with any questions. Thanks!

**Comment by ShivangiKakkar** [comment]
@punamdahiya Okay! Thanks.
 I am working on it. :)

**Comment by ShivangiKakkar** [comment]
@punamdahiya @chenba I am not able to understand the setup of this. Would you please help me with that? Sorry for being this late! (was facing some health issues)
Thanks :)

**Comment by punamdahiya** [comment]
@ShivangiKakkar [Edit button](https://github.com/mozilla-services/screenshots/blob/master/server/src/pages/shot/view.js#L369) shows a badge to highlight edit button. Show and hide of this [badge/highlight](https://github.com/mozilla-services/screenshots/blob/master/server/src/pages/shot/view.js#L342) is [controlled by](https://github.com/mozilla-services/screenshots/blob/master/server/src/pages/shot/controller.js#L16)  [local storage](https://developer.mozilla.org/en-US/docs/Tools/Storage_Inspector) hasSeenEditButton.

This issue is seen on hover of badge which is missing title attribute and thus missing tooltip. Adding the needed title on badge should help fix this issue. 

Please note look of edit button has changed in dev but underlying issue is still the same. Hope this helps. Thanks!

**Comment by punamdahiya** [comment]
I hope I answered your setup question right :) , for screenshots installation and setup we have  instruction here https://github.com/mozilla-services/screenshots#installation-and-setup , and always feel free to ask with the error if there is a particular step you are stuck on.

**Comment by ShivangiKakkar** [comment]
> I hope I answered your setup question right :) , for screenshots installation and setup we have instruction here https://github.com/mozilla-services/screenshots#installation-and-setup , and always feel free to ask with the error if there is a particular step you are stuck on.

@punamdahiya Yes! Thanks a lot :)

**Comment by ShivangiKakkar** [comment]
@punamdahiya Hey, I am getting this server build failed error. Do I need to install `postgres`  too or should I jump to the next step?

**Comment by punamdahiya** [comment]
> @punamdahiya Hey, I wanted to ask few queries, I am getting this server build failed error. Do I need to install `postgres` too or should I jump to the next step?

@ShivangiKakkar for running local server, you need to install postgres. Thanks

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
