### ISSUE TITLE
[Annotations] The drawing wrongly becomes opaque after using the highlighter tool

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#4472]
[Affected versions]:
- Nightly 62.0a1
- Screenshots 32.1.0 dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the Screenshots 32.1.0 dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on a new clean profile. 
- Have a saved shot link.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites and navigate to the saved shot link.
2. Click the "Edit this image" button.
3. Select the "Highlighter" tool and choose any color other than black.
4. Draw a line on the image and observe the behavior.

[Expected result]:
- The line is transparent.

[Actual results]:
- After the mouse is released the line becomes 100% opaque. 

[Notes]:
- Here is a screen recording with the issue:
![highligter opaque](https://user-images.githubusercontent.com/19226534/40232898-711ac444-5aa9-11e8-998a-f11fb5cc2232.gif)

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using the latest Firefox Screenshots 32.1.1 dev version installed from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html), on latest Nightly build 62.0a1(2018-05-21), on Windows 10 x64, Mac 10.13.3 and Arch Linux 4.12. The drawing is no longer opaque, but transparent, after using the Highlighter tool.
