### ISSUE TITLE
"Take A Screenshot" erroneous date format

### ISSUE THREAD

**Issue by Palfoe** [mozilla-services/screenshots#4480]
the "Take a Screenshot" firefox feature saves with the wrong date formatting, it does 2018-5-13, instead of the proper 2018-05-13.  This messes up the alphabetical order.

**Comment by Softvision-CristinaBadescu** [comment]
Thanks for reporting this. However, this issue has already been fixed in #4197  on the latest Firefox Screenshot 32.1.0 dev version (you can install it from [here](https://screenshots.dev.mozaws.net/homepage/install-test-local.html)).
This means that the issue will be fixed in the next version of Screenshots.
