### ISSUE TITLE
[FxA] Remove Time selection and add favorites for FxA users

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/screenshots#4688]
Per the spec: https://mozilla.github.io/testpilot-assets/Firefox_Screenshots/NEW_FxA_Integration/shot

We still need  clear indicator favorited shots on the my shots page

**Comment by 6a68** [comment]
Tasks
- remove expiration picker code
- add 'favorite' to DB schema (maybe)
- add heart icon
- replace 'infinity' icon with 'heart' icon on favorited for shots page view
- handle favoriting on server (changing expiration from 2 weeks to infinity and back)
- make all current infinite images favorited images

**Comment by chenba** [comment]
Since Favorites is a FxA feature and there are users with grandfathered in indefinitely saved shots who might not be FxA users, we need to the keep infinity symbol for those users.

**Comment by chenba** [comment]
Not sure why this wasn't auto-closed when the PR was merged.  Closing and moving it back to the proper sprint.

**Comment by chenba** [comment]
@SoftVision-CosminMuntean This is on dev now.  It's not using the new UI but the functionality is there.

**Comment by SoftVision-CosminMuntean** [comment]
Thanks @chenba! However, I have a two questions related this functionality:

1. Now that we remove time selection and add favorites for FxA users, when the user is not logged in or doesn't mark the shot as favorite, when the shot will expire? After 14 days? If yes, shouldn't we inform the users that the shot expires after 14 days?

2. If a shot it's marked as favorite, after you disconnect from your account instead of the "heart" icon the "infinite" icon is displayed on at the bottom right corner of the shot tile in "My Shots" page (see this [screenshot](https://drive.google.com/open?id=1GDW026fXxaF1u5H7kQ7g4lFiZaKreXZk)). Is this intended?

/cc @johngruen
