### ISSUE TITLE
Failure to load subtitle link favicon using /proxy?url

### ISSUE THREAD

**Issue by punamdahiya** [mozilla-services/screenshots#4738]
[Steps to reproduce]:
    - Save a shot
    - Paste the saved shot's link in Chrome.
    - Console shows message Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by punamdahiya** [comment]
<img width="1376" alt="console-error-chrome" src="https://user-images.githubusercontent.com/597734/43666883-90ed5dd2-972a-11e8-95e6-93682e28cafd.png">

**Comment by punamdahiya** [comment]
Issue reported in #4710 could be fall out of this error in Google Chrome 
https://github.com/mozilla-services/screenshots/issues/4710#issuecomment-410107827
Also, This call seems to be redundant as favicon for subtitle link is hidden https://github.com/mozilla-services/screenshots/issues/4710#issuecomment-410361130

**Comment by punamdahiya** [comment]
LInks to see issue in dev,stage and prod
https://screenshots.dev.mozaws.net/HxOj9GaxPyZc8ity/www.facebook.com
https://screenshots.stage.mozaws.net/hnjHvFJIrNdLE3yW/www.theatlantic.com
https://screenshots.firefox.com/97dlRupgFyXtHvxX/www.facebook.com

**Comment by 6a68** [comment]
Looks like `createProxyUrl` (in `proxy-url.js`, called when creating the shot page) assumes a regular https URL for a favicon, while we are saving the favicon as a data-URI.

Indeed, if you look at the data submitted in the `PUT` request when creating a new shot, the favicon is indeed saved as a base64 image, rather than, say, `https://facebook.com/favicon.ico`:

<img width="1382" alt="screen shot 2018-08-03 at 3 35 06 pm" src="https://user-images.githubusercontent.com/96396/43668637-d18b29d4-9732-11e8-86a4-6d02514a5794.png">

**Comment by 6a68** [comment]
When the shot is created in the background page, we get the favicon URL from `Tabs.tab.favIconUrl`:

https://github.com/mozilla-services/screenshots/blob/master/addon/webextension/background/takeshot.js#L13

<img width="795" alt="screen shot 2018-08-03 at 3 45 35 pm" src="https://user-images.githubusercontent.com/96396/43668895-4cb51ce0-9734-11e8-86c5-6d0cc26e3069.png">

 Apparently this API now returns a data-uri instead of the URL of the original favicon.

**Comment by 6a68** [comment]
Ah yeah, it turns out that the addons code just gets the favicon from tabbrowser (deeper code in Firefox), and some favicon refactoring there resulted in the image itself, not its URL, being returned by `tabs.Tab.favIconUrl`.

This is definitely an upstream bug; I'll update this issue when I get a BMO link for the Firefox bug to fix it.

In the meantime, we should just stop loading the favicon on the server pages altogether.
