### ISSUE TITLE
Increase or remove vertical size limit

### ISSUE THREAD

**Issue by 0xgggggggg** [mozilla-services/screenshots#4922]
The current pixel limit of 10000px is not large enough to capture long webpages, such as media features.

For an example, with my current size settings I can only capture about half of this feature article on the nytimes published today:

https://www.nytimes.com/interactive/2018/09/20/us/politics/russia-interference-election-trump-clinton.html

 screenshots/webextension/buildSettings.js.template

**Comment by clouserw** [comment]
10000px has been our limit due to memory and file size limitations.  It's not something we want to revisit right now, but you should be able to download the image locally instead of uploading it and see the whole image.  In this case, that is also broken, and I've filed #4925 to address that.  Thanks for bringing this to our attention!

**Comment by 0xgggggg** [comment]
I never get a haywire message, it crops at 10000px vertical before I can click the the save button.

**Comment by chenba** [comment]
@0xgggggggg The preview is misleading.  (It's been addressed in #4205 but it's not released yet.)  Copy and download don't have that limit.  However, that particular NYT page is larger than the current limits of a [canvas](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API), which is what Screenshots use to capture the page.  So in this case, even copy/download wouldn't work.
