### ISSUE TITLE
[FxA] My Shots Show a Settings Link when User is Not Signed In

### ISSUE THREAD

**Issue by chenba** [mozilla-services/screenshots#4938]
#### STR

1. Go to /shots when you are not signed through FxA

#### Expected

Sign In link in the header

#### Actual

Settings link in the header

**Comment by punamdahiya** [comment]
On disconnect, setting accountId cookie expire to a past date should fix this issue.
https://github.com/mozilla-services/screenshots/blob/master/server/src/server.js#L790

**Comment by punamdahiya** [comment]
Disconnect device logic seems to be working fine. I am not able to replicate this issue on https://screenshots.dev.mozaws.net hinting its localhost domain specific.

@chenba does this issue show up a) localhost or in dev as well? b) Does this happen right after disconnect or on browser restart

**Comment by punamdahiya** [comment]
@chenba to fix this issue for me on local, I had to delete screenshot test profile and restart

**Comment by chenba** [comment]
Doesn't seem to be happening with dev.  Closing.

**Comment by SoftVision-CosminMuntean** [comment]
I have managed to reproduce this issue on Screenshots (34.0.0) dev version if I'm logged into FxA and I reinstall Screenshots dev version.

[Prerequisties]:
- The latest Screenshots (34.0.0) dev version is installed.
- You are logged in into a valid FxA.

[Steps to Reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to "about:addons" page and remove the Screenshots add-on.
3. Navigate to "https://screenshots.dev.mozaws.net/homepage/install-test-local.html" and reinstall the add-on.
4. Navigate to "My Shots" page and observe the behavior.

[Expected Results]:
- You are no longer logged in and the "Sign In' button is displayed.

[Actual Results]:
- You are no longer logged in but the "Settings" button is displayed. If the button is clicked you are redirected to the Sign In page.

[Notes]:
- Here is a screen recording with the issue:
![reinstall the addon](https://user-images.githubusercontent.com/19226534/45943044-766fe880-bfed-11e8-9b90-e49e13f558e9.gif)

**Comment by punamdahiya** [comment]
I am able to replicate the issue with below STR

   - Open the browser with the profile from prerequisites.
   -  Navigate to "about:addons" page and remove the Screenshots add-on.
   -  Navigate to "https://screenshots.dev.mozaws.net/homepage/install-test-local.html" and reinstall the add-on.
 - Take a shot and hit save 
   -  Navigate to "My Shots" page and observe the behavior.

Please note I am not able to replicate the issue without step 'Take a shot and hit save'.

Debugging the underlying issue seems to be, post install of add-on and first upload registrationInfo in browser IndexedDb storage get changed and has different deviceId, causing 
a) New DeviceId to have accountId null in devices table
b) AccountId cookie stays for the dev domain causing button label to shows 'Settings'.
Initial deviceId
<img width="1369" alt="before install- deviceid" src="https://user-images.githubusercontent.com/597734/45972668-33177900-bff1-11e8-9965-865518530151.png">
DeviceId after uninstall and re-install add-on and first upload of shot
<img width="1371" alt="afterinstall-deviceid" src="https://user-images.githubusercontent.com/597734/45972674-36126980-bff1-11e8-917e-65520d88bee3.png">

Proposed fixes
a) Remove accountId cookie on install of addon
b) Fix browser  storage to return consistent deviceId

**Comment by 6a68** [comment]
@punamdahiya Are your STR different than Cosmin's? Did you sign into FxA before removing / reinstalling the dev addon?

**Comment by punamdahiya** [comment]
@6a68 Steps are same, I was logged into FxA before uninstall and install of add-on. My findings the reason for this bug is on install of add-on registration info is null because of which a new deviceId is generated.

**Comment by ianb** [comment]
I've created [Bug 1494390](https://bugzilla.mozilla.org/show_bug.cgi?id=1494390) about the issue of browser.storage.local persistence
