### ISSUE TITLE
Sometimes the delete button is replaced by a second share button

### ISSUE THREAD

**Issue by FatOrangutan** [mozilla-services/screenshots#4967]
![gif](https://user-images.githubusercontent.com/8336638/46192187-d92bf180-c317-11e8-87c2-f95b7e733cab.gif)

Haven't got any reproducible steps for now. FWIW, a page reload fixes the issue.
Screenshots v33.0.0 on Nightly 64.0a1 (2018-09-25)

**Comment by chenba** [comment]
None of us have seen this bug.  We'll try to reproduce it.

**Comment by chenba** [comment]
Those buttons are rendered on the server side and they do not change on the client side.  But more importantly, we've revamped the header since, so I think we could close this.

@FatOrangutan Thanks for reporting this!  We've made some changes to the header and the buttons in it, so the code no longer reflect what caused the bug you've noticed.

@johngruen @punamdahiya Hope there's no object to me closing this issue.
