### ISSUE TITLE
[FxA] Non-Firefox users shots page with zero shots

### ISSUE THREAD

**Issue by punamdahiya** [mozilla-services/screenshots#4991]
Non-blocking bug to update shot page when user is not uathenticated. As of now user gets redirected to homepage

When user is authenticated we show shots page with message "No saved shots, Go on, create some"

**Comment by youwenliang** [comment]
@punamdahiya For non-firefox users can they login with their firefox account to view their shots? (Currently there's no sign in button)

If there is a sign in button we should let non-firefox users stay at the zero shots page where they can click sign in to view their synced shots.

If there's no sign in button at all, then showing a zero shots page doesn't make sense since there's no actionable thing for users to do. We could redirect users to homepage right away instead of showing "looking for shots" in My Shot page.

**Comment by punamdahiya** [comment]
> @punamdahiya For non-firefox users can they login with their firefox account to view their shots? (Currently there's no sign in button)
> 
With https://github.com/mozilla-services/screenshots/pull/4966 , we are allowing login for non-firefox users to view their shots from homepage.

> If there is a sign in button we should let non-firefox users stay at the zero shots page where they can click sign in to view their synced shots.
> 
If user logs in successfully and have zero shots, below screen shows

<img width="1387" alt="logged-in-zero-shots" src="https://user-images.githubusercontent.com/597734/47053234-e131c100-d160-11e8-826a-48dd7a1650da.png">


> If there's no sign in button at all, then showing a zero shots page doesn't make sense since there's no actionable thing for users to do. We could redirect users to homepage right away instead of showing "looking for shots" in My Shot page.
If a user is not logged in and tries to access /shots page link directly, we show looking for shots with signin banner on top (screenshot below) and redirects user to home page after 10 seconds


<img width="1350" alt="not-logged-in-shots" src="https://user-images.githubusercontent.com/597734/47053242-e858cf00-d160-11e8-99bb-d8d62e99966b.png">

**Comment by youwenliang** [comment]
@punamdahiya Got it, thanks!
So what's our goal for this particular issue? Do we want to show something else when users have zero shots?

**Comment by punamdahiya** [comment]
@youwenliang that's correct, if we can improve on messaging ""No saved shots, Go on, create some" for non-Firefox users. @johngruen thoughts?

**Comment by weivicky** [comment]
@youwenliang @punamdahiya  Hey, I'm the old design intern here!  Is this done? I can help out or with other ux design issues.

**Comment by weivicky** [comment]
I put together a file that includes my feedback and possible solutions on the original empty states.  https://docs.google.com/document/d/1pNd-2LGzMk7bgA8XG4Gcw168_kVmtjCbcOBaGH34394/edit?usp=sharing 
<img width="962" alt="image" src="https://user-images.githubusercontent.com/10877399/48084240-2d52ad00-e1c5-11e8-9269-9e4e9b9cd6cd.png">

**Comment by marniepw** [comment]
Hey @weivicky! These look great. @johngruen is at a work week for the rest of the week, but I want to make sure he sees your designs. Thanks for jumping back in!

**Comment by weivicky** [comment]
@marniepw Hello again and thanks Marnie! :) Nice speaking to you again. Hope you are doing well!

I designed my mockups according to my assumptions about the type of users, goals, entry points, but they might be wrong. 😅

If someone can verify the assumptions for me, I can change my mockups accordingly.

**Here are my assumptions, which need to be verified.**

**User who is not on Firefox and not logged in  (current)**
Platform
- Not Firefox

Entry points
- Copying and pasting the link 

What are the those users trying to do? How did they get there?
- Accessing their own or other people's screenshots?
- Accidentally copied and pasted the wrong link (maybe wanted to copy and paste the Firefox Screenshot landing page link although unlikely) to it with friends,?
- Accidentally clicked on the link on the search engine (although unlikely)? 

Tasks
- Login to access screenshots
- Learn more about Firefox Screenshot (if they accidentally stumbled upon the link, although not very likely) - maybe we can have it in the footer or something
- Help & documentation (want to access screenshots but they do not know how) 

Actions suggested
- Login
- Learn more about Firefox? (it would be nice if there is an option to access "My shots" on the landing page for Firefox Screenshots" as we are promoting the feature that users can access their screenshots across devices)
- Help & documentation, if there is any

**User who is not on Firefox and finally logged in (current)**
Platform
- Not Firefox

Entry points
- Copying and pasting the link and logged in for users not on Firefox 

What are the those users trying to do? How did they get there?
- Accessing their own or other people's screenshots?

Tasks
- See their screenshots

Actions suggested
- Download Firefox (or if the software can detect whether or not the user has Firefox browser installed, "open firefox browser") to create more screenshots - Most likely they would have Firefox already. However, it would remind them that they need Firefox to use the feature.

**Comment by weivicky** [comment]
Hi, @johngruen @youwenliang!! If you guys can give me an update before Friday, I'd really appreciate it :D Thanks!

**Comment by youwenliang** [comment]
> I put together a file that includes my questions (regarding type of users, entry point, and goals), feedback and possible solutions on the original empty states. https://docs.google.com/document/d/1pNd-2LGzMk7bgA8XG4Gcw168_kVmtjCbcOBaGH34394/edit?usp=sharing
> 
> Mockups that accompany with my suggestions. Since I was not 100% what the users are up to, I have lots of mockups. I also tried adding a divider between the title and the empty space to make it more obvious that the space below the heading is reserved for saved shots. You can ignore the divider:
> 
> I wonder if we should include a title? Currently, the page just tells me I am on "Firefox Screenshots" but there are many other "Firefox Screenshots" places, such as the actual screenshot function page, the landing page.
> ![image](https://user-images.githubusercontent.com/10877399/48104330-087c2b00-e201-11e8-855c-972ad37f7fe2.png)
> 
> **Not on Firefox browser, not signed in** (I actually think the last one makes the most sense since the primary task should be signing in since they need to copy and paste the link to get to this page?)
> ![image](https://user-images.githubusercontent.com/10877399/48295419-92becc00-e459-11e8-9ea8-a4d83c025626.png)
> ![image](https://user-images.githubusercontent.com/10877399/48295426-a407d880-e459-11e8-8514-7e020af7722d.png)
> 

For not on Firefox, not signed in, I like that you put the sign in related information in the center as the main call to action. We could add a button below the sign in button to let users visit our screenshot homepage instead of automatically redirect to the homepage. And we can use a banner on the top to inform users that Firefox Screenshots is brought to you by Firefox with a download firefox button.

> **Not on Firefox browser, signed in**
> ![image](https://user-images.githubusercontent.com/10877399/48295441-bc77f300-e459-11e8-8d36-072068c9dc33.png)
> ![image](https://user-images.githubusercontent.com/10877399/48294570-fbef1100-e452-11e8-8edf-689ee0c8c6e4.png)
> 

For not on Firefox, signed in, I think we could reuse the banner I mentioned above to prompt users to download firefox, and then use the same illustration you proposed for the Firefox browser users to encourage users to take shots.

> **On Firefox browser (optional)**
> ![image](https://user-images.githubusercontent.com/10877399/48298455-e6e2a400-e48b-11e8-9226-225a1aa9fa28.png)
> ![image](https://user-images.githubusercontent.com/10877399/48298463-f8c44700-e48b-11e8-943c-53700037a83d.png)

I like the treatment here for sign in and not sign in users.

**Comment by weivicky** [comment]
With the fixes! Thanks for your feedback! Here are the updated versions!

Not on Firefox browser, not signed in - I still prefer v2. The reason why is that the only way to access screenshots.firefox.com/shots is by entering it into the URL bar (can’t find it on Google or anything), so I assume that most of them know what the page is for since they had to copy it from the saved shots page on Firefox browser. If most of the users know what the page is for (somewhat obvious from the URL too), I was thinking, it made more sense to prompt them straight to the sync login page (with a message that says “Continue to Screenshots”) immediately. I couldn’t think of a use for the page with the sign in CTA button in the middle. 

![image](https://user-images.githubusercontent.com/10877399/48638595-166b4200-e99f-11e8-9961-dc2ac6624d5b.png)

**Comment by youwenliang** [comment]
> Thanks for your feedback! Here are the updated versions for users accessing the /shots page directly! @youwenliang
> 
> **Not on Firefox browser, not signed in** - I prefer V2. The reason why is that the only way to access screenshots.firefox.com/shots is by entering it into the URL bar (can’t find it on Google or anything), so I assume that most of them know what the page is for since they had to copy it from the saved shots page on Firefox browser. If most of the users know what the page is for (somewhat obvious from the URL too), I was thinking, it made more sense to prompt them straight to the sync login page (with a message that says “Continue to Screenshots”) immediately. I couldn’t think of a use for the page with the sign in CTA button in the middle.
> 
> I think we can use the same empty screen for accessing /settings page (#5185) directly on non-Firefox browser to simplify things.
> 

I was thinking the same thing, both /shots and /settings could redirect to a FxA sign in page for non-firefox, not signed in users. Any thoughts @punamdahiya?

> Let me know what you think!
> 
> ![image](https://user-images.githubusercontent.com/10877399/48639413-85e23100-e9a1-11e8-9081-f19e48e6a130.png)

**Comment by weivicky** [comment]
Hi @punamdahiya! 

If you could answer the following questions, I would appreciate it! 

1. Will there be a persistent download Firefox banner on every page of Screenshots on a non-Firefox browser after login. 
When I open the URL for a specific shot on Chrome, I see a download Firefox banner. So, I assume there would a persistent download button banner after I login. Is this correct?

2. Wondering if we can detect whether or not someone has Firefox installed while looking at shots on Chrome/other browsers. If the user has Firefox browser (and we can detect it), maybe we don't need to show a download banner and have a CTA for opening Firefox instead. Would be cool for data as well.

**Comment by punamdahiya** [comment]
> Hi @punamdahiya!
> 
> If you could answer the following questions, I would appreciate it!
> 
>     1. Will there be a persistent download Firefox banner on every page of Screenshots on a non-Firefox browser after login.
>        When I open the URL for a specific shot on Chrome, I see a download Firefox banner. So, I assume there would a persistent download button banner after I login. Is this correct?
> 

Get Firefox now ( Upsell banner ) in header only shows on non-owned shots (in non-Firefox browsers). By non-owned shot, it means someone has shared the shot page url  and you don't have that shot linked to your firefox account.

To link a shot to your firefox account, you should be on the device where you have taken that shot in Firefox and signin with your firefox account.

>     2. Wondering if we can detect whether or not someone has Firefox installed while looking at shots on Chrome/other browsers. 
In screenshots server, we don't have that capability right now

**Comment by weivicky** [comment]
@punamdahiya 

Thanks!!

What do you thinking about showing it on every page after login? I was thinking it makes sense because it encourages users to download Firefox (as there's easy access to the banner). I included the banner in my mockup for empty state for /shots page after login on non-Firefox browser.

Also, referring back to Mark's question, what do you think about both /shots and /settings (and any other account related pages) redirecting to a FxA sign in page for non-firefox, not signed in users.

**Comment by punamdahiya** [comment]
> I was thinking the same thing, both /shots and /settings could redirect to a FxA sign in page for non-firefox, not signed in users. Any thoughts @punamdahiya?
> 

For now as a fix of #5185, in the initial launch users are redirected to homepage for all browsers. Including @johngruen for product take on redirecting to Firefox Account signin page only on non-Firefox browser.

**Comment by punamdahiya** [comment]
> @punamdahiya
> 
> Thanks!!
> 
> What do you thinking about showing it on every page after login? I was thinking it makes sense because it encourages users to download Firefox (as there's easy access to the banner).

Thought behind not showing Get Firefox upsell banner on owned individual shot pages is,  user have taken those shots and probably have access to Firefox.

>  I included the banner in my mockup for empty state for /shots page after login on non-Firefox browser.

+1

> Also, referring back to Mark's question, what do you think about both /shots and /settings (and any other account related pages) redirecting to a FxA sign in page for non-firefox, not signed in users.

just replied to the comment  :)

**Comment by weivicky** [comment]
Good points! Incorporated your feedback in the updated mockups. @punamdahiya

Hey @johngruen! 

This week, could you please post feedback for me (**should only take 10 minutes**) on the mockups below?

I am trying to get it done because I won’t have much time after this week since projects deadlines and exams are coming up (I think you also might have all hands soon too?)

In case the problems aren’t clear from the series of posts…
1. Design a screen for accessing /shots page directly on a non-Firefox browser before login 
2. Design an empty state for /shots page on a non-Firefox browser after login
3. (Optional) empty state for users on Firefox browser 

**The reasons Mark and I have for redirecting to FxA sign in page from accessing shots directly:** The only way to access screenshots.firefox.com/shots is by entering it into the URL bar (can’t find it on Google or anything), so I assume that most of them know what the page is for since they had to copy it from the saved shots page on Firefox browser. If most of the users know what the page is for (somewhat obvious from the URL too), I was thinking, it made more sense to prompt them straight to the sync login page (with a message that says “Continue to Screenshots”) immediately.

![image](https://user-images.githubusercontent.com/10877399/48801799-4b4b0200-ecdb-11e8-9d88-f99b59a8745d.png)

Thank you so much!!! I would greatly appreciate if you could let me know before the end of this week. Hope everything is going well!

**Comment by johngruen** [comment]
I think doing a redirect may be a little aggressive and it limits our ability...for that state i prefer:

![image](https://user-images.githubusercontent.com/3323249/48858281-910dd600-ed80-11e8-8e65-06f96accab9a.png)

For not on firefox/signed in, i prefer v1

For the Firefox browser, version, i actaully prefer the original icon (the one with the bear reaching for the page action)

**Comment by weivicky** [comment]
![image](https://user-images.githubusercontent.com/10877399/49043297-9f049200-f198-11e8-8251-9f806178badf.png)

Hi! here are the updated mocks!

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
