### ISSUE TITLE
[Edge] "FSI" and "PDI" unicode characters are wrongly displayed in the expiry details of a shot and in the "Sign In" promo banner

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/screenshots#5216]
[Affected Versions]:
- Microsoft Edge 42.17134.1.0

[Affected Platforms]:
- Windows 10

[Prerequisites]:
- You are not logged in with FxA.
- Have a link to the saved shot.

[Steps to reproduce]:
1. Open the Microsoft Edge browser and navigate to a saved shot page.
2. Observe the "Sign in banner" from the top of the page.
3. Observe the expiry details displayed under the title of the shot.

[Expected result]:
- The "Sign In" banner and the expiry details are correctly displayed.

[Actual result]:
Step 2: The "FSI" unicode character is displayed at the beginning of the sign in banner and the "PDI" unicode character is displayed at the end of promo baner.
Step 3: The "FSI" and "PDI" unicode characters are displayed beside the numbers.

[Notes]:
- Attached a screenshot of the issue:
![edge fsi and pdi](https://user-images.githubusercontent.com/19226534/48906245-86306f80-ee6c-11e8-8801-91ad262e9428.png)

**Comment by punamdahiya** [comment]
This issue is similar to https://github.com/mozilla-services/screenshots/issues/4863. Fix of #4863 was reverted in  https://github.com/mozilla-services/screenshots/pull/5025 due to failing localization.

We can use this issue to fix reverted PR with recommended fix  from @stasm  https://github.com/mozilla-services/screenshots/pull/4994#discussion_r228138203

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
