### ISSUE TITLE
Turn off FxA marketing

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#5254]
This include #5253, but also the top bar promotion of FxA.

**Comment by 6a68** [comment]
This and #5253 should be really easy, just need to set all the promo-related `shouldShow` functions to return `false` in the [PromotionStrategy](https://github.com/mozilla-services/screenshots/blob/master/server/src/promotion-strategy.js). Sadly, that refactoring turned out to be incredibly prescient
