### ISSUE TITLE
zh-hk should display Traditional Chinese

### ISSUE THREAD

**Issue by ITDogDogDick** [mozilla-services/screenshots#5347]
At https://screenshots.firefox.com/, when the first language is set to zh-hk, Firefox Screenshots displays Simplified Chinese. It should display Traditional Chinese, just like zh-tw.

https://discourse.mozilla.org/t/zh-hk-should-display-traditional-chinese/27793

**Comment by ianb** [comment]
@flodolo: can you comment on this? (I don't think this is the same issue as [Bug 1520446](https://bugzilla.mozilla.org/show_bug.cgi?id=1520446), but maybe?)

**Comment by flodolo** [comment]
I'm confused by the discussion in discourse: we don't have zh-HK on the website or in Firefox, we have zh-TW.

What's your accept-language if you visit this website?
http://www.reliply.org/tools/requestheaders.php

If you only have `zh` after `zh-HK`, I think it's expected that Fluent falls back Simplified Chinese.

I think at some point we discussed about having a special case for zh-HK in [fluent-langneg](https://github.com/projectfluent/fluent.js/blob/master/fluent-langneg/src/subtags.js#L29), but I don't remember in which context.

cc @stasm

**Comment by ITDogDogDick** [comment]
>>If you only have zh after zh-HK

This is the case. For your info, Hong Kong is using Traditional Chinese.
For example, when you visit Microsoft or Apple Hong Kong site, it is showing Traditional Chinese.
As a result, the fallback of zh-HK should be zh-TW.

**Comment by ITDogDogDick** [comment]
I have further tested on the accept language.

zh-HK,zh;q=0.8,en-US;q=0.5,en;q=0.3
zh-HK,zh-TW;q=0.8,zh;q=0.6,en-US;q=0.4,en;q=0.2
For both cases, https://screenshots.firefox.com/ displays Simplified Chinese.

However for both cases, https://www.mozilla.org/ redirects to https://www.mozilla.org/zh-TW/. This is what is expected for Screenshots. zh-HK should be directly fall back to zh-TW at server side.

**Comment by stasm** [comment]
After digging into `fluent-langneg` code and comparing it to `LocaleService.cpp`, I think I can confirm that this is a bug in `fluent-langneg`. It comprises three parts.

1. The list of likely subtags in `fluent-langneg` is limited. It currently doesn't include data fro many locales, including `zh-HK`.
2. The matching algorithm in `fluent-langneg` is missing an extra step. After the region of the requested language is set to `*`, `LocaleService.cpp` tries to add likely subtags _again_. In combination with the step in which the requested region is cleared, this allows the algorithm to correctly select `zh-HK` based on the script used.
3. The list of available locales claims to be _unordered_, but in reality it uses its inherent ordering in some of the steps of the algorithm.

In other words, what currently happens is:

1. Request `zh-HK`.
1. Clear the region → `zh-*`.
1. Match against `zh-*-CN-*` and `zh-*-TW-*`.
1. Return `zh-CN` followed by `zh-TW`.

After adding the missing likely subtags, the bug persists:

1. Request `zh-HK`.
1. Add the likely subtag → `zh-Hant-HK`.
1. Clear the region → `zh-Hant-*`.
1. Match against `zh-*-CN-*` and `zh-*-TW-*`.
1. Return `zh-CN` followed by `zh-TW`.

Here's what should happen instead when we add the missing step to the algorithm:

1. Request `zh-HK`.
2. Add the likely subtag → `zh-Hant-HK`.
3. Clear the region → `zh-Hant-*`.
4. Add the likely subtag again → `zh-Hant-TW`.
5. Match against  `zh-*-TW-*`.
6. Return `zh-TW`.

I filed https://github.com/projectfluent/fluent.js/issues/334 against `fluent-langneg`. I'll update this issue when the bug is fixed.

**Comment by zbraniecki** [comment]
I released https://www.npmjs.com/package/fluent-langneg 0.1.1 which should address this!

**Comment by ianb** [comment]
This issue is being closed (without being fixed) because [we are discontinuing the Screenshots server](https://blog.mozilla.org/futurereleases/2019/01/24/clarifying-the-future-of-firefox-screenshots/).
